### ISSUE TITLE
Trying to Reach phone

### ISSUE THREAD

**Issue by Nidre** [Aluxian/Whatsie#10]
Not sure if its a Whatsie  issue or WhatsApp issue but this is the error I'm getting. Both phone and PC are connected to the same network and can access to internet.
![whatsie 20160226 203148](https://cloud.githubusercontent.com/assets/6220948/13361545/0a95b460-dcc8-11e5-9b6e-43acd12b9201.png)

**Comment by Aluxian** [comment]
That's not something that would not work because of Whatsie. Did https://web.whatsapp.com/ work for you?

**Comment by Nidre** [comment]
Well it works. Actually Whatsie started work after a while too, maybe it was just a connection issue.

**Comment by Aluxian** [comment]
Cool! If the issue comes back, feel free to reopen.
