### ISSUE TITLE
Request: Close with escape key

### ISSUE THREAD

**Issue by iliyang** [Aluxian/Whatsie#103]
I've been using Messenger for Desktop for a few days and it's awesome! I installed Whatsie portable foe Windows now and it's awesome too, but I miss the ability to close the chat window with the escape key on my keyboard. Would it be possible to implement that?

I love that Whatsie has a portable version for Windows! I wish Messenger had too.

Cheers,
Iliyan

**Comment by Aluxian** [comment]
Messenger for Desktop 2 will have a portable version, too! I'm working on it :)

As for the feature you requested, I'll add it as a preference in the menu.

**Comment by iliyang** [comment]
Wohoo, thanks, for both! And for the instant response :+1:

**Comment by Aluxian** [comment]
I wouldn't call 30 minutes instant, haha. But thanks! I'm glad you're happy about it 😄

**Comment by iliyang** [comment]
I think it qualifies as instant by feature request standards :)

**Comment by Aluxian** [comment]
Right ;)

-- 
Alexandru Rosianu
Full-Stack Developer
aluxian.com | startersquad.com

On 21 April 2016 at 19:22:51, Iliyan Georgiev (notifications@github.com) wrote:

I think it qualifies as instant by feature request standards :)

**Comment by Aluxian** [comment]
This should be live in the latest update (2.0.15).
