### ISSUE TITLE
Behavioural detection detects Spyware: "LAN Bypass Backdoor"

### ISSUE THREAD

**Issue by 28Black** [Aluxian/Whatsie#107]
* Operating system: Windows 7 64-bit Professional 
* Whatsie version: 2.0.14

Emsisoft Anti-Malware prevents starting Whatsie because it detects a "LAN Bypass Backdoor" in this software. Malware definitions are up-to-date, Manual scanning (just the .exe / with Kaspersky IS2016 & Emsisoft) doesn't find anything - it's the behavioural detection which warns at startup.

I'll attach a screenshot.
![ashampoo_snap_2016 04 22_18h19m58s_001_emsisoft anti-malware 11-6 - alert](https://cloud.githubusercontent.com/assets/4772696/14748143/6d834c88-08b8-11e6-8482-2f2977a6fbf8.jpg)

**Comment by Aluxian** [comment]
It must be a false positive. I think it detected behaviour similar to what's described here:

http://support.emsisoft.com/topic/18293-lan-bypass-backdoor/

> because these Putty version tries with no visible user interface to establish a network connection. This behavior is typical for Backdoor Malware and therefore is the message of behavioral analysis

Even though Whatsie *does* have a window, it's not displayed as soon as the app starts. Or, I don't know, maybe something else triggered the alert. I'd like to know what triggered it because this way I'd understand what's going on, but it's probably not possible to have the antivirus say exactly what happened.

**Comment by 28Black** [comment]
The log of Emsisoft doesn't tell me any more deeper information. The log reveals also a detected "Code Injection"... Maybe that's the issue?! (See screenshot)
![ashampoo_snap_2016 04 22_19h07m29s_001_emsisoft anti-malware](https://cloud.githubusercontent.com/assets/4772696/14749090/c1f2409e-08bd-11e6-9892-951ebc606c27.jpg)

**Comment by Aluxian** [comment]
Do you have atom.io installed? If you do, is it detected as well?

**Comment by Aluxian** [comment]
Another sign that it's a false positive:

> Spyware and download behavior are caused by the asynchronous start up of Internet Explorer. It starts downloading stuff before showing it's GUI so it triggers a lot of the rules designed to look out for processes that download files in the background without any feedback to the user. 

http://support.emsisoft.com/topic/16540-question-behavior-blockeramn-alerts-and-internet-explorer/

It might also be triggered because of how Chromium works (Whatsie uses Electron which uses Chromium).

**Comment by 28Black** [comment]
No atom.io is not installed (I dont even know what it is :D).
Ok, I'll low it and try to inform Emsisoft of the "false positive" to get you on a whitelist. Your code is open sourve I guess so they can confirm non-spyware behaviour.

**Comment by Aluxian** [comment]
Awesome, thanks! I hope they'll add it. I'll close this, just ask if you have other question.

Atom.io is a text editor, mostly used for programming.
