### ISSUE TITLE
Toggling Launch on Startup off throws exception

### ISSUE THREAD

**Issue by Nidre** [Aluxian/Whatsie#11]
Wasn't possible to copy the error so here is a screenshot of the issue. This also appears when Whatsie is launched on startup every day.

Windows 10
Whatsie v2.0.5 (win32:installer, 135)
win32 ia32 10.0.10586

![error 20160315 000234](https://cloud.githubusercontent.com/assets/6220948/13761461/6a733b42-ea41-11e5-8f54-8bfd43d1aaf1.png)

**Comment by Aluxian** [comment]
Nice catch, thank you! I found why it was crashing when you tried to disable it and I fixed it. However, is this the same error that occurs when Whatsie is launched on startup? I'll upload a build soon for you to test it.

**Comment by Nidre** [comment]
@Aluxian It was happening on startup too a bit while ago. But haven't seen that happen for a while now.

**Comment by Aluxian** [comment]
Cool! Please reopen if it occurs again.
