### ISSUE TITLE
Tray Icon

### ISSUE THREAD

**Issue by leoheck** [Aluxian/Whatsie#110]
* Operating system: Ubuntu 15.10
* Whatsie version: 2.0.14-beta

The same issue as other alternatives... it lacks tray icon.

**Comment by marcosfede** [comment]
same here on ubuntu 16.04. Any workarounds to get the tray icon so the app keeps running in the background?

**Comment by Aluxian** [comment]
@leoheck Please read the answer above and reopen if it still doesn't work.

**Comment by leoheck** [comment]
This is why I give my thumbs up for @marcosfede. Thank you guys!!!
