### ISSUE TITLE
Settings like Icon in Gnome Shell

### ISSUE THREAD

**Issue by temaoz** [Aluxian/Whatsie#118]
* Operating system: Fedora Workstation 23, Gnome Version 3.18.2
* Whatsie version: 2.0.14-beta

My Gnome Shell Icon looks like the attached image. I would prefer a whatsapp like icon. Is there a way to change the icon?
![bildschirmfoto von 2016-04-25 11-10-26](https://cloud.githubusercontent.com/assets/16197929/14779100/b58dfa80-0ad6-11e6-85ac-97ac96f96a8d.png)

**Comment by Aluxian** [comment]
What/where is that icon? I'm not an everyday user of Gnome Shell.

**Comment by temaoz** [comment]
It's the dock icon in the Gnome Shell. At least for me.

**Comment by Aluxian** [comment]
Can you attach a bigger screenshot with the entire dock?

-- 
Alexandru Rosianu
Full-Stack Developer
aluxian.com | startersquad.com

On 25 April 2016 at 12:16:44, temaoz (notifications@github.com) wrote:

It's the dock icon in the Gnome Shell. At least for me.

**Comment by temaoz** [comment]
Of course. Here you are.
![bildschirmfoto von 2016-04-25 11-19-07](https://cloud.githubusercontent.com/assets/16197929/14779273/af6edec0-0ad7-11e6-8032-997f67d3f534.png)

**Comment by Aluxian** [comment]
Ooh. That's not what it's supposed to look like. Shouldn't your Gnome Shell use icons from `/usr/share/icons/hicolor/`? That's where Whatsie installs the dock icon.

Btw it looks awesome!

**Comment by temaoz** [comment]
Thanks!
Yes, that would be what the Shell is supposed to do. I checked the folder and the Whatsie icons are existing there. But for some reason it won't set an icon. I'll attach an image how it looks like without the icon theme.
![bildschirmfoto von 2016-04-25 11-22-08](https://cloud.githubusercontent.com/assets/16197929/14780054/476ba502-0adb-11e6-9bd0-aff878ed9b5d.png)
