### ISSUE TITLE
Add a NotifyIcon in the lowerleft corner of the Whatsie I...

### ISSUE THREAD

**Issue by Aluxian** [Aluxian/Whatsie#119]
**Description:**
Add a NotifyIcon in the lowerleft corner of the Whatsie Icon on the Taskbar to display the amount of unread messages, so you don't have to look it manually in case there might have been a message while you were afk

**Best thing about Whatsie:**
Ease of use,

**Worst thing about Whatsie:**
That there is no NotifyIcon which displays the amount of unread messages in the Taskbar

**Extra:**
How about to set our Background ourselves? I love the Sephia Color theme (which I just realized isn't Sepia, I was wondering why it wasn't brownish. What is a Sephia anyway), but I don't like the background as much.

Maybe even let us define our own themes based on existing ones. Like a ColorPicker for every color used in the Theme

**Comment by Thursty** [comment]
That is mine. I confused myself a little bit with the NotifyIcon lol
What I meant was something like this 
https://db.tt/3YqwyGd2

But I guess/hope that was clear from the start lol

**Comment by Aluxian** [comment]
That's called a badge, and I've added it already. It'll be in the next version (I want to add a few more things and test before I release it).

**Comment by Thursty** [comment]
Badge! That's what I was looking for!
That's great to here, looking forward to the new version

**Comment by zunder** [comment]
@Aluxian how about putting it in brackets into the title bar, like in telegram:
[https://imgur.com/RebCOVM](https://imgur.com/RebCOVM)

**Comment by Aluxian** [comment]
I added a counter in the window title as well. I'll create a new issue for customizable themes.

**Comment by Aluxian** [comment]
https://github.com/Aluxian/Whatsie/issues/124
