### ISSUE TITLE
I'd like an option to be offline without having to close ...

### ISSUE THREAD

**Issue by Aluxian** [Aluxian/Whatsie#130]
**Description:**
I'd like an option to be offline without having to close Whatsie. Could there be an option that as long as the window is active and then if it's inactive (so in the background) it registers me as offline. That would be cool!

**Best thing about Whatsie:**
Ease of use,

**Worst thing about Whatsie:**
It doesn't automatically make a smiley out of ":)" like skype does... but that's about it

**Extra:**

**Comment by TheGreatHap** [comment]
Sorry Just noticed that was already a feature... Anyway I love Whatsie! :D

**Comment by Aluxian** [comment]
No problem! :)

The feature that allows converting symbols to emojis is tracked here: https://github.com/Aluxian/Whatsie/issues/129
