### ISSUE TITLE
I am not able to login to my Whatsapp Account.
Nothing ha...

### ISSUE THREAD

**Issue by Aluxian** [Aluxian/Whatsie#138]
**Description:**
I am not able to login to my Whatsapp Account.
Nothing happens after scanning the QR-Code.

**Steps to reproduce:**
Open Whatsie
Scan QR-code using WhatsApp on phone (Version: 2.16.56)

**App version:**
2.0.14

**OS:**
Linux

**Extra:**
Nice application!

**Comment by Aluxian** [comment]
@op, if you're seeing this issue: are you able to log in using web.whatsapp.com?

**Comment by antsas** [comment]
yes, there is no problem using the website.
It seems like the problem only occurs when I'm using the beta version of the phone client. The problem doesnt occur using the current stable version (2.16.42).

**Comment by Aluxian** [comment]
Thanks! I will install WhatsApp beta and check myself. I might have a clue why it's not working. In the mean time, can you please try Whatsie v2.0.12? Does that one work? (If you're on Windows, you can get the portable version to check quickly).

**Comment by antsas** [comment]
Still the same behavior using Whatsie v2.0.12

**Comment by Aluxian** [comment]
Hmm. Then, I don't know. I'll try whatsapp beta next week and see what's wrong. Thanks again for helping 😄

**Comment by antsas** [comment]
After deleting ~/.config/Whatsie/ it seems to work now in combination with the WhatsApp Beta.

**Comment by Aluxian** [comment]
When it wasn't working... Was that the first time you used Whatsie? Or did you use Whatsie before and it worked?

**Comment by antsas** [comment]
I am using Whatsie already for two weeks. It stopped working yesterday (30th), after WhatsApp pushed some (beta) updates. Before these updates, it worked fine.

**Comment by renearts** [comment]
Same issue here as well!

**Comment by Aluxian** [comment]
I can't reproduce this, it worked for me (WhatsApp beta 2.16.60 and Whatsie 2.0.14). @antsas and @renearts, can you please open Dev Tools (View > Toggle Dev Tools), switch to the Console tab, then copy and paste here what's in there?

**Comment by renearts** [comment]
This morning I received a Whatsapp update to beta 2.16.60 and it all seems to work again. For me the issue can be closed.

**Comment by antsas** [comment]
@Aluxian Opening the Dev Tools doesnt seem to work on Linux. There is just a white gap right next to the (main) screen. [http://www.directupload.net/file/d/4346/qdnh3ogn_png.htm](http://www.directupload.net/file/d/4346/qdnh3ogn_png.htm)
But after deleting ~/.config/Whatsie/ (as already mentioned earlier), Whatsie is working again without any problems.

**Comment by Aluxian** [comment]
@antsas was that a one-time fix or do you have to delete that folder regularly?

**Comment by antsas** [comment]
@Aluxian I have deleted the folder only once

**Comment by Aluxian** [comment]
Ok, so everybody can login now. I'm going to close this issue because I don't know what to fix or how. I'm glad it works for you.


--
Alexandru Rosianu Full-Stack Developer aluxian.com | startersquad.com On Thu, May 05, 2016 at 10:28 PM, antsas < notifications@github.com [notifications@github.com] > wrote:
@Aluxian [https://github.com/Aluxian] I have deleted the folder only once
