### ISSUE TITLE
Improve gulp error messages

### ISSUE THREAD

**Issue by Aluxian** [Aluxian/Whatsie#143]
> what do I have to do in order to get whatsie build? It always tells me Error in plugin 'gulp-electron-downloader' Message: Failed to retrieve information from the GitHub API. (Ubuntu 16.04)

**Comment by Taskkill** [comment]
Can you tell me how you solved it?
Thanks.

**Comment by Aluxian** [comment]
See this about GH tokens: https://github.com/Aluxian/Whatsie#build

As far as I can remember, that's how it was solved
