### ISSUE TITLE
Why are you using 'import' instead of 'require'

### ISSUE THREAD

**Issue by TimNZ** [Aluxian/Whatsie#151]
What are you reasons for this?

It slows down development as I have to do a build each time, or gulp watch.

**Comment by Aluxian** [comment]
It's the ES6 way. You have to do a build each time because the whole Javascript is ES6, so you need babel to compile it for most features to work.

**Comment by TimNZ** [comment]
Ahh fair enough, I see Node 5.11 only has 58% ES2015 compat vs 96% for Node 6.
And I see Electron is on Node 5.10

Thanks

**Comment by Aluxian** [comment]
Where did you get those stats? Where can I see what features are included in that 96% you mentioned? I think it'd be awesome to give up babel if chromium can run ES6 just as well.


--
Alexandru Rosianu Full-Stack Developer aluxian.com | startersquad.com On Fri, May 06, 2016 at 8:15 AM, TimNZ < notifications@github.com [notifications@github.com] > wrote:
Ahh fair enough, I see Node 5.11 only has 58% ES2015 compat vs 96% for Node 6.
And I see Electron is on Node 5.10

Thanks

**Comment by TimNZ** [comment]
http://node.green/

**Comment by Aluxian** [comment]
Nice, thanks.

--
Alexandru Rosianu Full-Stack Developer aluxian.com | startersquad.com On Fri, May 06, 2016 at 8:47 AM, TimNZ < notifications@github.com [notifications@github.com] > wrote:
http://node.green/ [http://node.green/]
