### ISSUE TITLE
Title bar

### ISSUE THREAD

**Issue by DotTheI** [Aluxian/Whatsie#154]
* Operating system: OSX
* Whatsie version: 2.0.14.96

Currently the title bar looks like this:
![2016-05-09 9 23 21](https://cloud.githubusercontent.com/assets/10737439/15105194/ba183926-15d0-11e6-8159-7fc6784e65a9.png)
Would be nice to have it look like this (taken from ChitChat):
![2016-05-09 9 23 41](https://cloud.githubusercontent.com/assets/10737439/15105202/cd31da08-15d0-11e6-9566-1571e89a2641.png)

**Comment by Aluxian** [comment]
Tracked here: https://github.com/Aluxian/Whatsie/issues/1
