### ISSUE TITLE
Whatsie is not starting on startup (Ubuntu 16.04 LTS Xeni...

### ISSUE THREAD

**Issue by Aluxian** [Aluxian/Whatsie#167]
**Description:**
Whatsie is not starting on startup (Ubuntu 16.04 LTS Xenial, kernel 4.4.0), despite being ticked to do so in options. It looses its tick in startup applications.

**Steps to reproduce:**
Adding the app to startup applications manually

**App version:**
2.0.14

**OS:**
Linux

**Extra:**
Keep up the good work!

**Comment by turtlehunter** [comment]
Can confirm. Ubuntu 16.04

**Comment by RomanLier** [comment]
Same happens to me on 14.04

**Comment by RomanLier** [comment]
Fixed it on Ubuntu 14.04 with the Startup Apps dialog. Check the picture.
![area de trabajo 1_051](https://cloud.githubusercontent.com/assets/2019766/16547986/960bc57e-4155-11e6-9201-9156925ba763.png)

**Comment by Aluxian** [comment]
Hey, this should be fixed in the latest version. Check for update inside the app or download Whatsie again from https://github.com/Aluxian/Whatsie/releases/tag/v2.0.18
