### ISSUE TITLE
Dark theme makes Whats App content invisible

### ISSUE THREAD

**Issue by Nidre** [Aluxian/Whatsie#17]
Other themes seems to be fine but as soon as I switch to Dark theme this is what happens:

![whatsie 20160325 095906](https://cloud.githubusercontent.com/assets/6220948/14040485/4eceb380-f270-11e5-98c1-afc967901632.png)

**Comment by Aluxian** [comment]
I saw this myself and I fixed it recently. I just haven't uploaded an updated build yet. Thanks for the feedback!
