### ISSUE TITLE
Website does not work

### ISSUE THREAD

**Issue by demoneaux** [Aluxian/Whatsie#173]
The website linked to in the repo, http://whatsie.chat/, does not work, and shows GitHub Pages' default 404 page. Was it deleted mistakenly?

**Comment by Aluxian** [comment]
It's just unpublished, I'll publish it Tuesday :)

--
Alexandru Rosianu Full-Stack Developer aluxian.com | startersquad.com On Sun, May 15, 2016 at 12:42 PM, Benjamin Tan < notifications@github.com [notifications@github.com] > wrote:
The website linked to in the repo, http://whatsie.chat/ [http://whatsie.chat/] , does not work, and shows GitHub Pages' default 404 page. Was it deleted mistakenly?

**Comment by Aluxian** [comment]
Fixed! ^^
