### ISSUE TITLE
Clicking Whatsie taskbar icon unsnaps window

### ISSUE THREAD

**Issue by wigster** [Aluxian/Whatsie#179]
* Operating system: Win 10.586.318 x64
* Whatsie version: 2.0.14

Clicking the Whatsie icon from Task Bar notification area resizes the Whatsie window if it is snapped to half/quarter screen, returning it to the unsnapped size.

**Comment by Aluxian** [comment]
Thanks! Tracked here: https://github.com/Aluxian/Whatsie/issues/73
