### ISSUE TITLE
Hide the menu bar

### ISSUE THREAD

**Issue by bil-elmoussaoui** [Aluxian/Whatsie#190]
The menu bar looks ugly on Linux as Electron/Chrome still uses GTK2. 
I think adding the possiblity to hide the menubar would be awesome! this was added to Electron and so to Atom too
Thanks!

**Comment by Aluxian** [comment]
Hey, this should be live in the latest version. Check for update inside the app or download Whatsie again from https://github.com/Aluxian/Whatsie/releases/tag/v2.0.18
