### ISSUE TITLE
Re opening the application if it's on tray

### ISSUE THREAD

**Issue by bil-elmoussaoui** [Aluxian/Whatsie#191]
As with Messenger desktop, if the application is hidden on tray (minimized) clicking on the executable file should show the window instead of doing nothing
I'm having this issue on Linux with the latest version of Whatsie!
Thanks

**Comment by Aluxian** [comment]
Can you please test the latest version (2.0.15)?

**Comment by bil-elmoussaoui** [comment]
I would love to, but the Arch aur package is outdated :(  If you're a maintainer, can you please replace the `pkgver=2.0.14` to `pkgver=2.0.15`?

**Comment by Aluxian** [comment]
I pinged the maintainer. I'll let you know when it's updated.

**Comment by bil-elmoussaoui** [comment]
Fixed! Thanks :+1:
