### ISSUE TITLE
No icon, starts with the OS without setting it so, and non systay icon.

### ISSUE THREAD

**Issue by 19darion91** [Aluxian/Whatsie#192]
* Operating system: Ubuntu Mate 16.04 amd64
* Whatsie version: 2.0.14

Whatsie starts processes with the OS - there is no command in startup applications and there is no command given by me to start, but it is there in the processes, taking away RAM and CPU usage.

Also the app itself doesn't have an Icon when it is open and is in my WIndows List plug-in for Mate Panel.

And lastly, I wouldn't mind it running in the bacground if i could close/minimize it to the notification area/ system tray.

**Comment by Aluxian** [comment]
You activated "Launch on Startup", right? That feature doesn't currently work well. I'll ship a fix in 2.0.15, but I'm not sure whether it'll fix it once and for all, we'll see.

**Comment by 19darion91** [comment]
Thanks for the quick respond.
No, I never set any app to launch on Startup. And actually disable things that have set them self to do so.

**Comment by Aluxian** [comment]
Hey, this should be fixed in the latest version. Check for update inside the app or download Whatsie again from https://github.com/Aluxian/Whatsie/releases/tag/v2.0.18
