### ISSUE TITLE
Add chang font option

### ISSUE THREAD

**Issue by Aluxian** [Aluxian/Whatsie#193]
**Description:**
Add chang font option

**Best thing about Whatsie:**
Design

**Worst thing about Whatsie:**
Change font

**Extra:**

**Comment by johnfb76** [comment]
please I need to change the font in Unofficial WhatsApp to Tahoma
 
pleaae help

**Comment by Aluxian** [comment]
Thanks! Tracked here: https://github.com/Aluxian/Whatsie/issues/24

**Comment by johnfb76** [comment]
Thank you Aluxian

I dont know what to do ... to install the font-manager for Whatsir
please can you show me in details where should I input the code you send "font-manager" 
I have no backfround in modern programming

thank you
  ----- Original Message -----

**Comment by Aluxian** [comment]
There's nothing you can do right now, I have to add it.

--
Alexandru Rosianu Full-Stack Developer aluxian.com | startersquad.com On Sun, May 22, 2016 at 10:14 AM, johnfb76 < notifications@github.com [notifications@github.com] > wrote:
Thank you Aluxian

I dont know what to do ... to install the font-manager for Whatsir
please can you show me in details where should I input the code you send "font-manager"
I have no backfround in modern programming

thank you
----- Original Message -----

**Comment by johnfb76** [comment]
Ok thanks

by the way messenger for desktop take the same font that you choose for mozilla maybe because its html .. but it is so slow comparing to whatsie.
  ----- Original Message -----

**Comment by Aluxian** [comment]
Sorry, I couldn't understand everything you said about Messenger for Desktop.

What about Mozilla? The font that Messenger for Desktop uses is independent from any other app, because it's isolated.

What exactly is slower than Whatsie? Just curious.

Thanks!

--
Alexandru Rosianu Full-Stack Developer aluxian.com | startersquad.com On Sun, May 22, 2016 at 10:32 AM, johnfb76 < notifications@github.com [notifications@github.com] > wrote:
Ok thanks

by the way messenger for desktop take the same font that you choose for mozilla maybe because its html .. but it is so slow comparing to whatsie.
----- Original Message -----

**Comment by johnfb76** [comment]
I mean Dear Aluxian look at the picture .. why the font is Tahoma by default in Messenger for Desktop .. and how it can be for Whatsie as long as its the same core programming system

The slower is the performance of Messenger for Desktop it opens and process the chat very slowly especially when you make a video or audio call via messenger .. its more heavier on the laptop or the system

Greetings




  ----- Original Message -----

**Comment by Aluxian** [comment]
I don't set the fonts manually. Whatsie uses the font that web.whatsapp.com and MFD uses what messenger.com uses. Have patience, I'm tracking this feature and when I or a contributor will have time, it'll be implemented. MFD 2 will be as performant as Whatsie.

**Comment by johnfb76** [comment]
Thats great I will wait
  ----- Original Message -----
