### ISSUE TITLE
can you please use native notifications? i received a mes...

### ISSUE THREAD

**Issue by Aluxian** [Aluxian/Whatsie#201]
**Description:**
can you please use native notifications? i received a message and noticed only because of the green tray icon

**Best thing about Whatsie:**
Ease of use, Design

**Worst thing about Whatsie:**
not official icon i guess

**Extra:**
maybe a nice feature would be to expand the size of the chat through css to the full window.

another thing would be to keep the chat icons visibles despite the theme, for example i like faded and pure because they're minimal, but i lose the chat icons..

**Comment by manuel-delverme** [comment]
+1
on ubuntu + i3 i don't even get the toast/notification, it used to work in the older client

**Comment by Aluxian** [comment]
@op What operating system are you using?

**Comment by manuel-delverme** [comment]
```
➜  ~ uname -a
Linux tableflip 3.19.0-59-generic #66-Ubuntu SMP Thu May 12 22:35:27 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
➜  ~ cat /etc/issue
Ubuntu 15.04 \n \l

```

**Comment by manuel-delverme** [comment]
➜  ~ uname -a                        
Linux my_pc 3.19.0-59-generic #66-Ubuntu SMP Thu May 12 22:35:27 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
➜  ~ cat /etc/issue
Ubuntu 15.04 \n \l

**Comment by Aluxian** [comment]
@manuel-delverme Can you please check Whatsie 2.0.15?

**Comment by manuel-delverme** [comment]
do i still need to check?

**Comment by Aluxian** [comment]
That'd be nice, so that I know this feature works now.

**Comment by manuel-delverme** [comment]
yea still not working
