### ISSUE TITLE
Cool app, the problem is that I can't send voice messages...

### ISSUE THREAD

**Issue by Aluxian** [Aluxian/Whatsie#204]
**Description:**
Cool app, the problem is that I can't send voice messages. Thank you!

**Steps to reproduce:**
I speak with friends in Teamspeak3 or Discordapp, but when I hit the button to send a voice message in Whatsie, it starts recording, but never sends the message when I hit the "okay/tick" button.

**App version:**
2.0.14-beta

**OS:**
OS X

**Extra:**
Nice support, I love this cause being open sourced and technologically advanced. Good job.

**Comment by jserodio** [comment]
Hey it's me the one who sent this issue via typeform. Just wanted to say that the OS is not OSX, but Windows 10.

**Comment by Aluxian** [comment]
Thanks for the report.

**Comment by Aluxian** [comment]
Hey @jserodio, does it work in https://web.whatsapp.com/?

**Comment by Aluxian** [comment]
Closed for inactivity
