### ISSUE TITLE
Can't download Whatsie for Mac

### ISSUE THREAD

**Issue by Nikki1993** [Aluxian/Whatsie#208]
Can't download Whatsie for Mac, getting 

> Error 1001 Ray ID: 2aa96c9cc18b37b0 • 2016-05-29 10:57:14 UTC
> DNS resolution error

On Chrome 51.

**Comment by jgsa** [comment]
This issue also occurs for the Windows version. Same error.

> Error 1001 Ray ID: 2aaea6d9562c1fb8 • 2016-05-30 02:10:47 UTC
DNS resolution error

**Comment by Aluxian** [comment]
Fixed! Sorry for this :(
