### ISSUE TITLE
[Linux] App doesn't open when minimized in system tray

### ISSUE THREAD

**Issue by Aluxian** [Aluxian/Whatsie#214]
>When I have whatsie minimized in the system tray, I can't open it with the left click button in Linux(Arch + Cinnamon) as I can do in Windows 10.

**Comment by davidgasquez** [comment]
Please let me know if I can help sending any logs :smile:

**Comment by Aluxian** [comment]
Hey, does this work now? (version 2.0.15)

**Comment by davidgasquez** [comment]
Hey there @Aluxian! Everything seems working seamlessly right now! 

Huge thanks :smile:

**Comment by Aluxian** [comment]
Wonderful! :)
