### ISSUE TITLE
I'm really sorry if this is already a feature (but I can'...

### ISSUE THREAD

**Issue by Aluxian** [Aluxian/Whatsie#220]
**Description:**
I'm really sorry if this is already a feature (but I can't find it), but it might be a good idea to make a notification sound toggle. Normally I don't mind the sound, but while I'm listening to music on my speakers it's really annoying.

**Best thing about Whatsie:**
Design

**Worst thing about Whatsie:**
Developer tools are blank, I don't know what they have to do, but if possible I want to try it out.

**Extra:**
Hmm, except for the fact that I love what you made although I wanted to create a client for linux but you were faster. ;)

**Comment by Aluxian** [comment]
No, that's currently not a feature. but I want to add it. Progress tracked here: https://github.com/Aluxian/Whatsie/issues/6

Dev tools are used for debugging and editing some parts of the UI. Not useful if you're not a dev :)

**Comment by Aluxian** [comment]
> I wanted to create a client for linux but you were faster. ;)

Oh, by the way, you can join me and work together on Whatsie ;)

**Comment by TheNLGhost** [comment]
> Oh, by the way, you can join me and work together on Whatsie ;)

I already have another project going on now. But if I have some free time, I don't mind helping you out.

**Comment by Aluxian** [comment]
@TheNLGhost 

If you decide to give it a shot, join me on Gitter: https://gitter.im/Aluxian/Whatsie. I'll answer any question you might have :)

Here's an overview (kanban style) with all the issues: https://huboard.com/Aluxian/Whatsie
