### ISSUE TITLE
Empty window: http://i.imgur.com/GycZcTV.png

### ISSUE THREAD

**Issue by Aluxian** [Aluxian/Whatsie#226]
**Description:**
Empty window: http://i.imgur.com/GycZcTV.png

**Steps to reproduce:**
Windows 10 LTSB N + install original whatsapp, remove it and install Whatsie ... empty window.

**App version:**
2.0.14 beta x86

**OS:**
Windows

**Extra:**

**Comment by CHEF-KOCH** [comment]
Sadly I can#t edit my own issue ticket. But I want to add that may an resource is missing on Windows 10 LTSB N since it exclude some stuff. I think we may need to check it and then implement it so that even if it's not on the system it's linked within the program itself.

**Comment by Aluxian** [comment]
Oh, haha. I'm glad it's fixed and thanks for replying :)
