### ISSUE TITLE
Add a way to trun off notifications

### ISSUE THREAD

**Issue by Aluxian** [Aluxian/Whatsie#227]
**Description:**
Add a way to trun off notifications

**Best thing about Whatsie:**
Ease of use

**Worst thing about Whatsie:**
cant turn off notifications and sound notifications!!

**Extra:**
more themes...

**Comment by bil-elmoussaoui** [comment]
I think this should be handled by the OS. In linux (Gnome) you can enable/disable notifications for each application
![capture du 2016-06-12 03-58-37](https://cloud.githubusercontent.com/assets/7660997/15988458/0e50628e-3052-11e6-84bb-cb033cb1f8d7.png)
You can also disable only sound notification or other settings..
![capture du 2016-06-12 03-58-25](https://cloud.githubusercontent.com/assets/7660997/15988459/12a26198-3052-11e6-8a04-8a61a958fbc8.png)

**Comment by Aluxian** [comment]
@bil-elmoussaoui I agree, and that's the way I want to go, eventually.

**Comment by Aluxian** [comment]
Duplicate of https://github.com/Aluxian/Whatsie/issues/68
