### ISSUE TITLE
Cannot find module 'semver'

### ISSUE THREAD

**Issue by dmaglio** [Aluxian/Whatsie#238]
* Operating system: Fedora 23
* Whatsie version: 2.0.15-453 x86_64
after last update cannot start

![screenshot at 2016-06-10 09 48 00](https://cloud.githubusercontent.com/assets/446573/15957670/e22bdd4e-2ef0-11e6-8ea0-5950f693a829.png)

**Comment by dmaglio** [comment]
after ```sudo dnf clean all``` and ```sudo dnf update``` i find last update (2.0.15-467) and works

**Comment by Aluxian** [comment]
Can you try to reinstall it? I added the module back, but the updated package was pushed to the repository under the same version (2.0.15) (I know, bad thing to do, I updated the CI config today and it won't do this again). I don't know if apt can recognise the change, though... So if you can't reinstall it, can you try to remove the repo, clear cache, and add it again?

Let me know how it works, I want to help you.

--
Alexandru Rosianu Full-Stack Developer aluxian.com | startersquad.com On Fri, Jun 10, 2016 at 10:51 AM, dmaglio < notifications@github.com [notifications@github.com] > wrote:
 * Operating system: Fedora 23
 * Whatsie version: 2.0.15-453 x86_64 after last update cannot start

[https://cloud.githubusercontent.com/assets/446573/15957670/e22bdd4e-2ef0-11e6-8ea0-5950f693a829.png]

**Comment by Aluxian** [comment]
Oh, awesome! :thumbsup:
