### ISSUE TITLE
computer not connected
make sure your computer has an act...

### ISSUE THREAD

**Issue by Aluxian** [Aluxian/Whatsie#239]
**Description:**
computer not connected
make sure your computer has an active internet connection

**Steps to reproduce:**
just launch it

**App version:**
2.0.15-beta

**OS:**
Windows

**Extra:**

**Comment by Aluxian** [comment]
Is that in a dialog or inside the app? A screenshot would help. Thank you.

**Comment by benewib** [comment]
![whatsie](https://cloud.githubusercontent.com/assets/9347046/15984530/920557ec-2ff8-11e6-83a7-baeb3bb913c9.png)

the working version is whatsie-2.0.14-win32-setup.exe, when an update showup and I press it. this is happen....
sorry for my english

**Comment by Aluxian** [comment]
Thanks! Does this website work for you? https://web.whatsapp.com/

**Comment by benewib** [comment]
yes, its work
when I reinstall with whatsie-2.0.14-win32-setup.exe, its work also

**Comment by Aluxian** [comment]
Having version 2.0.15 installed, can you please try to do the following?

1. Press `ctrl` + `alt` + `i`
2. Switch to tab `console`
3. Type `localStorage.debug = 'whatsie:*'`, press enter
4. Restart the app
5. Press `ctrl` + `alt` + `i`
6. Show me what it says in there

**Comment by benewib** [comment]
![toolwiz20166-11-23-24-40](https://cloud.githubusercontent.com/assets/9347046/15986185/be95b2b0-302b-11e6-934a-cdf5be22fd69.png)

**Comment by Aluxian** [comment]
I think Whatsie is being blocked by a firewall/antivirus on your computer, that's why it can't connect to the internet. Please check your firewall/antivirus software and whitelist (add an exception for) Whatsie.

**Comment by benewib** [comment]
when I run privatefirewall, Whatsie could work. Windows firewall may be causing all this
Thank you so much for your help

**Comment by Aluxian** [comment]
You're welcome! I'm glad it's solved.
