### ISSUE TITLE
Can't start Whatsie all of a sudden!

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [Aluxian/Whatsie#245]
* Operating system: Windows 7
* Whatsie version: v2.0.15-beta / v2.0.14-beta

https://i.imgur.com/uvgkbCO.png

**Comment by Aluxian** [comment]
So that happens in both v2.0.15-beta and v2.0.14-beta?

**Comment by Aluxian** [comment]
Was it after a fresh install or after an update? Do you know if it happened before v2.0.14-beta as well?

**Comment by Aluxian** [comment]
I can't reproduce it... Can you please uninstall and reinstall? Maybe it's because of some wrong preferences (which would be cleared by an uninstall).

**Comment by Unrepentant-Atheist** [comment]
I don't install. Ever. Always portable versions.

**Comment by Aluxian** [comment]
Do you have anything in these folders on your computer? (using the portable version, they shouldn't even exist)

```
C:\Users\<username>\AppData\Roaming\Whatsie
C:\Users\<username>\AppData\Local\whatsie
```

**Comment by Aluxian** [comment]
One more thing: the portable version stores preferences and other data inside the same folder. So unless you've done this before, you should try to download it again, unzip and run it.
