### ISSUE TITLE
Audio recording stops if windows are switched

### ISSUE THREAD

**Issue by orschiro** [Aluxian/Whatsie#253]
Dear @Aluxian,

Great latest release! Thank you!

I have found the following issue with:

* Operating system: Ubuntu 16.04
* Whatsie version: Latest Github deb package

1. Start an audio recording
2. Switch to another window
3. Return to Whatsie 

You will see that the recording has been stopped. 

Can you confirm this?

Thankfully,

~Robert

**Comment by Aluxian** [comment]
I confirm. That's how it works on https://web.whatsapp.com/ too. I don't know what the behaviour regarding this should be...

**Comment by Aluxian** [comment]
I'll file this as a feature request.

**Comment by orschiro** [comment]
Great, thank you!

  

Hopefully we can find a way around this.

  

Warmly,

  

~Robert

  

  

  

On Jun 13 2016, at 5:27 pm, Alexandru Rosianu &lt;notifications@github.com&gt;
wrote:  

> I'll file this as a feature request.

>

> —  
> You are receiving this because you authored the thread.  
> Reply to this email directly, [view it on
GitHub](https://github.com/Aluxian/Whatsie/issues/253#issuecomment-225615945),
or [mute the thread](https://github.com/notifications/unsubscribe/AAKbw-
idCsT4jsMt_cqV_xxgYISzEWB3ks5qLXbtgaJpZM4I0ZDx).![](https://github.com/notifications/beacon/AAKbwwDNLE1TWi6xksgV8-e-KSK4zjTmks5qLXbtgaJpZM4I0ZDx.gif)

**Comment by Aluxian** [comment]
I think this is the correct behaviour. I'm sorry, Robert, I can't help you with this one. Besides, changing it would be tricky because of how WhatsApp Web works.

**Comment by orschiro** [comment]
Dear @Aluxian,

I understand your position. Thanks though for getting back to me!

~Robert
