### ISSUE TITLE
[Linux] Use the envelope notification on Ubuntu

### ISSUE THREAD

**Issue by GijsTimmers** [Aluxian/Whatsie#267]
* Operating system: Ubuntu 16.04
* Whatsie version: 2.0.15-beta

It would be nice if the native 'message/email' notification could be used on Ubuntu. It's an envelope that turns blue whenever a new message arrives.

For example:

![qb0l6](https://cloud.githubusercontent.com/assets/972314/16169800/325ee904-353c-11e6-84df-8b5fdd923c00.png)

**Comment by Aluxian** [comment]
So basically you want the same functionality that Whatsie offers, but instead of having Whatsie's tray icon that turns green when you get a notification, you want Whatsie to turn that native icon blue instead?

**Comment by GijsTimmers** [comment]
Yes, exactly.

**Comment by Aluxian** [comment]
Why don't you use Whatsie's tray icon? It provides the same functionality. Besides, you can tell whether the notification is from Email or Whatsie, and you can open Whatsie by clicking the tray icon.

If Whatsie made that icon blue, how would you know you had a notification for Whatsie?

**Comment by GijsTimmers** [comment]
Just personal preference. The blue envelope, also called the [MessagingMenu](https://wiki.ubuntu.com/MessagingMenu/) is a feature of the operating system and it keeps the taskbar clean. Applications using this menu allow the user to click on it to see what the notification is about.

**Comment by Aluxian** [comment]
I probably can't do that because it'd require changing how notifications are sent. See, I don't send the notifications myself, but through [Electron](http://electron.atom.io/), which in turn uses `libnotify`.

I don't like this feature, sorry. I might change my mind if other users also request it, but it'll still be a bit of a technical challenge.
