### ISSUE TITLE
Spellchecker ES - Fedora x64

### ISSUE THREAD

**Issue by mlopezcoria** [Aluxian/Whatsie#268]
* Operating system: GNU/Linux Fedora 23 x86_64 Linux kernel 4.5.7-200
* Whatsie version: 2.0.15-beta

I've installed Whatsie using the RPM. I also installed hunspell-es but I have the "Spell Checker Language" combo empty. What's missing?

I use cinnamon desktop and the icon in the menu is also missing.

Regards.

**Comment by Aluxian** [comment]
That's a known bug in 2.0.15, fixed in 2.0.16 (almost ready for release, it's currently undergoing tests). I'll leave a message here when it's released.

**Comment by Aluxian** [comment]
Hey, this should be fixed in the latest version. Check for update inside the app or download Whatsie again from https://github.com/Aluxian/Whatsie/releases/tag/v2.0.18

**Comment by mlopezcoria** [comment]
Hey, now I've got version 2.0.19 and I can see the languages list, but even though I've got activated 'Check Spelling While Typing', Watsie doesn't mark any typo.
