### ISSUE TITLE
permission filesystem: 755  package: 775

### ISSUE THREAD

**Issue by jcmartins** [Aluxian/Whatsie#270]
* Operating system: Archlinux
* Whatsie version: latest 
when I run yaourt -S whatsie I have this message:
**warning: directory permissions differ on /usr/share/icons/hicolor/64x64/apps/
filesystem: 755  package: 775**

tks
joao

**Comment by Aluxian** [comment]
Thanks, I'll fix it when I update the build process to upload to AUR automatically.

**Comment by Aluxian** [comment]
Can you please install again? It should be fixed now.
