### ISSUE TITLE
Wondering about updating to beta vs stable releases

### ISSUE THREAD

**Issue by mzmousa** [Aluxian/Whatsie#279]
* Operating system: windows
* Whatsie version: latest

Hi, this isn't 100% a Whatsie question but I figure you might be able to help me!

I remember you mentioning that you were using Nuts as your release server at some point. You have stable and beta releases. When updating Whatsie, I realized you can set the update release channel, e.g., `stable`, `beta`, `dev`. How is this done in regards to `autoUpdater`? 

I see that your beta releases have -beta at the end of the releaseName, but not in the tag name. How do you set `autoUpdater.setFeedUrl(...)` to decide whether to upload to the latest `beta` or `stable` release? I'm trying to do something similar.

**Comment by mzmousa** [comment]
@develar Hi Vladimir, sorry to bother you! But if you knew anything about how I would do this (since you told me you're also using Nuts) would you have an idea? I'm trying to do something similar to [Whatsie](https://github.com/Aluxian/Whatsie) with a similar issue posted [here](https://github.com/Aluxian/Whatsie/issues/279)!

**Comment by Aluxian** [comment]
I use https://github.com/Aluxian/squirrel-updates-server, not nuts. Reasons are in a question issue there. I'll write a more elaborate answer tomorrow.

**Comment by mzmousa** [comment]
Ahh, I see! Sorry, that was someone else who was using Nuts. It seemed to me like it didn't handle updates for channel endpoints too well and I thought you had figured it out for your app - I'll just use your updates server instead :)
Thanks.

**Comment by develar** [comment]
@mzmousa Don't forget to create docs PR (sample config) to electron-builder ;) Feel free to file any issue if electron-builder an simplify something.

**Comment by mzmousa** [comment]
@develar Haha, I post so much that you're recognizing me now :grinning:
Absolutely! I'll see what I can do.
