### ISSUE TITLE
Windows installer for non-developers

### ISSUE THREAD

**Issue by Jamushroom** [Aluxian/Whatsie#3]
I'd love to try this app out but I'm not a developer for apps. So I'd love it if you'd add an installer for the OS-es for us non-app developers :)

**Comment by Aluxian** [comment]
Hey there! This is a work-in-progress currently. I need to finish a few things (e.g. automatic updates, a new website) and then I will upload a beta on [Gitter](https://gitter.im/Aluxian/Facebook-Messenger-Desktop) which everyone can test. I'll do this in one of the following days. After I release the beta and fix potential bugs or work on more features, I'll fully release the app for everyone to download.

**Comment by Jamushroom** [comment]
That is good news, thanks for letting us know! Can't wait to try this app out! :smile:

**Comment by Aluxian** [comment]
I have tested the Windows installer and it (finally) works well. I'll close this until I release the app and you get a chance to test it.
