### ISSUE TITLE
Whatsie went black trying to upload a video intro a group.

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Whatsie#300]
**Description:**
Whatsie went black trying to upload a video intro a group.

**Steps to reproduce:**
Drag and drop a clip of video from windows explorer to Whatsie

**App version:**
2.0.15-beta

**OS:**
Windows 10

**Works in WhatsApp Web:**
Yes

**Extra:**
[Not answered]

**Comment by Aluxian** [comment]
@aluxian-huginn please email op:

```
Thanks for the report. I have two questions:
1. What is the format of that video? .mp4? Something else?
2. How big is the video file in MB?
```

**Comment by aluxian-huginn** [comment]
@Aluxian Sent!

**Comment by punkguy48** [comment]
Yes, it's an mp4 file, about 15 MB.

**Comment by Aluxian** [comment]
I can't reproduce.

**Comment by Aluxian** [comment]
@punkguy48 Can you please try the latest version and see if it works? https://github.com/Aluxian/Whatsie/releases/tag/v2.0.18

**Comment by punkguy48** [comment]
same thing on version v2.0.18, now when trying to play a video :( sorry for the delay!
