### ISSUE TITLE
[Linux] Take link in chat and problem with url charset

### ISSUE THREAD

**Issue by romanlex** [Aluxian/Whatsie#309]
I get messages with link (maybe from MacOs)
![screenshot_20160711_184458](https://cloud.githubusercontent.com/assets/3369304/16736936/df097ff8-4797-11e6-81b3-ce58b0d0a4a3.png)
When I turn on the link from the message, then I get an error with url encoding
![screenshot_20160711_184509](https://cloud.githubusercontent.com/assets/3369304/16736984/0ceca2b0-4798-11e6-946b-92e79e083098.png)

* Operating system: Arch Linux
* Whatsie version: 2.0.15-beta

**Comment by Aluxian** [comment]
Hey, what happens if you right-click and try to copy that url? Does it copy with those weird characters or as it should?

**Comment by romanlex** [comment]
It happens when I click on link. There is a randomly. Some links has specified characters, many without this.

**Comment by Aluxian** [comment]
Hey, this should be fixed in the latest version. Check for update inside the app or download Whatsie again from https://github.com/Aluxian/Whatsie/releases/tag/v2.0.18
