### ISSUE TITLE
[production][] Command failed: 4294967295 System.AggregateException: One or more errors occurred...

### ISSUE THREAD

**Issue by Aluxian** [Aluxian/Whatsie#31]
[See this exception on Errbit](https://exceptions.whatsie.chat/apps/56eff7bd64da236b41000003/problems/56f82b0364da231acf000019)
# Command failed: 4294967295
```
Command failed: 4294967295 System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote name could not be resolved: 'updates.whatsie.chat' at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult) at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result) at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Squirrel.Utility.<LogIfThrows>d__50`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Squi
```
### URL ###
[app:///scripts/browser/managers/auto-update-manager.js](app:///scripts/browser/managers/auto-update-manager.js)"
### Occured ###
Mar 27  9:48pm

### Similar ###
1

## Params ##
~~~
{}
~~~

## Session ##
~~~
{}
~~~

## Backtrace ##
~~~
60:  C:\Users\Maximiliano\AppData\Local\whatsie\app-2.0.7\resources\atom.asar\browser\api\lib\auto-updater\auto-updater-win.js -> **AutoUpdater.emitError**
34:  C:\Users\Maximiliano\AppData\Local\whatsie\app-2.0.7\resources\atom.asar\browser\api\lib\auto-updater\auto-updater-win.js -> ****
70:  C:\Users\Maximiliano\AppData\Local\whatsie\app-2.0.7\resources\atom.asar\browser\api\lib\auto-updater\squirrel-update-win.js -> ****
52:  C:\Users\Maximiliano\AppData\Local\whatsie\app-2.0.7\resources\atom.asar\browser\api\lib\auto-updater\squirrel-update-win.js -> ****
87:  events.js -> **emitTwo**
172:  events.js -> **ChildProcess.emit**
200:  internal/child_process.js -> **Process.ChildProcess._handle.onexit**
~~~

## Environment ##
| Key        | Value      |
|------------|------------|
| process&amp;#46;pid | 3796 |
| process&amp;#46;cwd | C:\Users\Maximiliano\AppData\Local\whatsie\app-2.0.7 |
| process&amp;#46;execPath | C:\Users\Maximiliano\AppData\Local\whatsie\app-2.0.7\Whatsie.exe |
| process&amp;#46;version | v5.1.1 |
| process&amp;#46;argv | [&quot;C:\\Users\\Maximiliano\\AppData\\Local\\whatsie\\app-2.0.7\\Whatsie.exe&quot;, &quot;--squirrel-firstrun&quot;] |
| process&amp;#46;memoryUsage | {&quot;rss&quot;=&gt;69500928, &quot;heapTotal&quot;=&gt;29320032, &quot;heapUsed&quot;=&gt;19038552} |
| os&amp;#46;loadavg | [0, 0, 0] |
| os&amp;#46;uptime | 511378.1957465 |
| HTTP_USER_AGENT |  |

**Comment by mzmousa** [comment]
How did you fix this bug? I'm getting a similar one
