### ISSUE TITLE
Minimize  to tray optioncan be  useful in ubuntu.

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Whatsie#311]
**Description:**
Minimize  to tray optioncan be  useful in ubuntu.

**Operating system:**
Linux

**Best thing about Whatsie:**
Performance, Ease of use, Design

**Worst thing about Whatsie:**
missing minimize  to tray option

**Extra:**

**Comment by Aluxian** [comment]
It's already in the menu: Window > Show in tray
