### ISSUE TITLE
should have an option to deselect conversations, this way...

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Whatsie#314]
**Description:**
should have an option to deselect conversations, this way you will not read messages from conversation you don't want to, and you will not miss messages accidentally.

**Operating system:**
OS X, Windows, Linux

**Best thing about Whatsie:**
Performance, Ease of use

**Worst thing about Whatsie:**
cannot deselect conversations

**Extra:**
[Not answered]

**Comment by Aluxian** [comment]
I don't understand what you mean. Please describe your suggestion in other words or provide screenshots.
