### ISSUE TITLE
Whatsie crashes on launch

### ISSUE THREAD

**Issue by wigster** [Aluxian/Whatsie#315]
* Operating system: Win 10.586.494
* Whatsie version: 2.0.15

Since yesterday Whatsie fails when I try to launch it (see screenshot).

The only thing I can think of as having changed is my having upgraded to the latest cumulative update of Win 10 (.494) a couple of days ago.

![whatsie](https://cloud.githubusercontent.com/assets/10956987/16869773/cd459ab0-4a7e-11e6-97ba-087144c74ca9.JPG)

**Comment by Aluxian** [comment]
Hey, can you please try the latest version? `2.0.18`

**Comment by Aluxian** [comment]
From here: https://github.com/Aluxian/Whatsie/releases/tag/v2.0.18

**Comment by wigster** [comment]
HI Aluxian,

I've just upgraded to 2.0.18 but I have the same problem.

**Comment by Aluxian** [comment]
Thanks! Help me debug it, please:

1. [Open cmd](http://www.digitalcitizen.life/7-ways-launch-command-prompt-windows-7-windows-8)
2. Type `%LOCALAPPDATA%\whatsie\app-2.0.18\Whatsie.exe --debug` and press enter
3. Now you should see some logs on the screen. Scroll up, and just a few lines below the command you entered in step 2 you should see something like this:

```
Thu, 21 Jul 2016 08:42:55 GMT whatsie:C:\Users\IEUser\AppData\Local\whatsie\app-2.0.18\resources\app.asar\scripts\browser\utils\file-logger saving logs to "C:\Users\IEUser\AppData\Roaming\Whatsie\logs\1469090575856.txt"
```

Can you please send me the that .txt file (`C:\Users\IEUser\AppData\Roaming\Whatsie\logs\1469090575856.txt`)?

**Comment by wigster** [comment]
I'm attaching the logfile. But I've managed to make it work by nuking the whole thing and starting from scratch, so I am guessing it won't be showing the problem.

**Comment by Aluxian** [comment]
Ah, I've just seen your previous edit. If it doesn't crash anymore, attaching a log won't really help – it'll just say "everything is fine". I'm glad it works now :)
