### ISSUE TITLE
Hello. My whatsie is not working. I downloaded and instal...

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Whatsie#316]
**Description:**
Hello. My whatsie is not working. I downloaded and installed it, but when I open it it stays searching and never opens anything.

**Steps to reproduce:**
Open the app

**App version:**
Version 2.0.15-beta

**OS:**
Windows 7 64 bit

**Works in WhatsApp Web:**
Yes

**Extra:**
PLEASE HELP

**Comment by Aluxian** [comment]
@aluxian-huginn email op:

```
Please try the latest version, 2.0.18: https://github.com/Aluxian/Whatsie/releases/tag/v2.0.18
```

**Comment by aluxian-huginn** [comment]
@Aluxian Sent!
