### ISSUE TITLE
When I click on the appeared notification of the message,...

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Whatsie#328]
**Description:**
When I click on the appeared notification of the message, the whole application crashes. I am using 2.0.14 version on Yosemite

**Steps to reproduce:**
Get a notification, click on it

**App version:**
2.0.14 (tried stable and beta update channel)

**OS:**
OSX Yosemite

**Works in WhatsApp Web:**
It&#039;s not relevant for this issue

**Extra:**
[Not answered]

**Comment by Aluxian** [comment]
@aluxian-huginn please email op:

```
Hey, can you please try the latest version? 
https://github.com/Aluxian/Whatsie/releases/download/v2.0.16/whatsie-2.0.16-osx.zip
```

**Comment by aluxian-huginn** [comment]
@Aluxian Sent!

**Comment by ondrejfuhrer** [comment]
Hey @Aluxian, I just tried to download it and it seems it works fine. So the problem was that the app did not update itself through the channel. But not sure if it is wort investigation right now.

**Comment by Aluxian** [comment]
Hmm... Yeah, I don't know why you were still on 2.0.14. Anyway, I'm glad it's fine.
