### ISSUE TITLE
Add support to hide the menu bar via a shortcut, such as ...

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Whatsie#329]
**Description:**
Add support to hide the menu bar via a shortcut, such as Ctrl+M)

**Operating system:**
Windows, Linux

**Best thing about Whatsie:**
Ease of use, Design

**Worst thing about Whatsie:**
Integration with Linux Desktop

**Extra:**
[Not answered]

**Comment by Aluxian** [comment]
Already done in 2.0.16, shortcut is `Alt+Ctrl+B`
