### ISSUE TITLE
JavaScript error in the main process
https://i.imgur.com/...

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Whatsie#330]
**Description:**
JavaScript error in the main process
https://i.imgur.com/x5JF8ir.png

**Steps to reproduce:**
Receive a Message

**App version:**
2.0.16-dev

**OS:**
Windows 10

**Works in WhatsApp Web:**
Yes

**Extra:**
[Not answered]

**Comment by Aluxian** [comment]
2.0.17 released, please update or download it from here: https://github.com/Aluxian/Whatsie/releases
