### ISSUE TITLE
Always there is a JavaScript Error Popup

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Whatsie#331]
**Description:**
Always there is a JavaScript Error Popup

**Steps to reproduce:**
Just using 2.0.16-dev on Windows 8.1-64 ent

**App version:**
2.0.16-dev

**OS:**
Windows 8.1 entenpreis 64 Bitte

**Works in WhatsApp Web:**
Yes

**Extra:**
Screenshot of the Error Popup:
https://abload.de/img/clipboard-hp2500hmsau.jpg

**Comment by francwalter** [comment]
![graphic_19_07_2016 16_06_42](https://cloud.githubusercontent.com/assets/927269/16954079/c6c41c08-4dcf-11e6-904c-82df98e2010f.jpg)

**Comment by Aluxian** [comment]
Hey, thanks for reporting. I've just fixed it and now I'm building an update.


--
Alexandru Rosianu Full-Stack Developer aluxian.com | startersquad.com On Tue, Jul 19, 2016 at 5:42 PM, franc < notifications@github.com [notifications@github.com] > wrote:
[https://cloud.githubusercontent.com/assets/927269/16954079/c6c41c08-4dcf-11e6-904c-82df98e2010f.jpg]

**Comment by Aluxian** [comment]
2.0.17 released, please update or download it from here: https://github.com/Aluxian/Whatsie/releases

**Comment by francwalter** [comment]
Mann your fast :+1: Thank's!!!
