### ISSUE TITLE
Increasing font size of other language fonts

### ISSUE THREAD

**Issue by h0wdyd3wdy** [Aluxian/Whatsie#339]
* Operating system: Fedora 24 64bit
* Whatsie version: 2.0.15-beta

I often have to read both English and Arabic in Chats, but the Arabic font size is extremely small and I see no way to increase the font size/change the font, etc?

Is that possible?

**Comment by Aluxian** [comment]
That's not possible currently, but progress is being tracked here: https://github.com/Aluxian/Whatsie/issues/24
