### ISSUE TITLE
One click to open from systray.

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Whatsie#342]
**Description:**
One click to open from systray.

**Operating system:**
Linux

**Best thing about Whatsie:**
Performance, Ease of use, Design

**Worst thing about Whatsie:**
Hard to open from systray (Linux Mint). Need two clicks.

**Extra:**
Thank you for your app.

**Comment by Aluxian** [comment]
This should work... left click should focus the app. Maybe it's a bug on Linux Mint.

**Comment by Aluxian** [comment]
I'm sorry, I know this would be really useful but I can't help. It's a shortcoming of Electron, the framework I'm using, whose features are not compatible with every distro.
