### ISSUE TITLE
I don't get reply option on native notification on mac

### ISSUE THREAD

**Issue by rohitkhatri** [Aluxian/Whatsie#346]
* Operating system: Max OSX El Capitan 10.11.5 (15F34)
* Whatsie version: 2.0.18-dev (2.0.18.216)

When I get notification, I don't see reply option like native messenger does. But you have mentioned on your website "Native Notifications
(with reply on OS X)"

Can anyone tell me what's wrong?

**Comment by Aluxian** [comment]
I confirm, this is a regression. I'll check what's wrong and fix it. Thanks!

**Comment by rohitkhatri** [comment]
@Aluxian thanks to you :-)

**Comment by Aluxian** [comment]
Fixed in 2.0.19-beta.
