### ISSUE TITLE
Virus scan results

### ISSUE THREAD

**Issue by wickles** [Aluxian/Whatsie#35]
2/56 detections, please explain if possible: 

https://www.virustotal.com/en/file/45099d5caca54f8006feb99e1746a979fb947dd296215c94a8b263a56e023e8b/analysis/1459645090/

| Antivirus | Result                    | Update   |
|-----------|---------------------------|----------|
| Baidu     | Win32.Virus.Lamer.g       | 20160402 |
| Rising    | PE:Malware.RDM.07!5.D [F] | 20160403 |

**Comment by Aluxian** [comment]
Those are false positives.

I couldn't find any documentation about any of those results, so I don't know what is detected and why those AVs think the installer is malware. If you can find anything, let me know.

Atom has some false positives, too: https://github.com/atom/atom/issues/3927
And Electron: https://github.com/atom/electron/issues/4485

**Comment by Aluxian** [comment]
If you have any other questions, feel free to reopen this.

**Comment by wickles** [comment]
Thanks
