### ISSUE TITLE
The tray icon not showing in ubuntu.
Ubuntu Version: 14.0...

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Whatsie#352]
**Description:**
The tray icon not showing in ubuntu.
Ubuntu Version: 14.04
Whatsie: 2.0.18-dev

**Steps to reproduce:**
Install it in ubuntu I guess. Tray is grayed out and the icon does not appear

**App version:**
2.0.18-dev

**OS:**
14.04

**Works in WhatsApp Web:**
It&#039;s not relevant for this issue

**Extra:**
[Not answered]

**Comment by Aluxian** [comment]
@aluxian-huginn email op:

```
Fixed in 2.0.19-beta. Please update or download again.
```

**Comment by aluxian-huginn** [comment]
@Aluxian Sent!
