### ISSUE TITLE
Dragging an image into the wrong area of whatsie puts the...

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Whatsie#356]
**Description:**
Dragging an image into the wrong area of whatsie puts the image in the whatsie window and then it stays stuck like that. The image being all that shows, beside top bar/options and scroll bar on right. Closing window and reopening doesn't fix it. I tried toggling different views, chats, etc. It's just my image with the cursor icon as the toggle zoom/magnifying glass. Must exit and relaunch app.

**Steps to reproduce:**
all info contained above^^

**App version:**
2.0.15-beta Arch Linux package

**OS:**
Antergos Linux (a flavor of Arch Linux)

**Works in WhatsApp Web:**
I haven&#039;t tried

**Extra:**
thank you for your app!

**Comment by Aluxian** [comment]
@aluxian-huginn Email user:

```
Please update to the latest version from whatsie.chat
```

**Comment by aluxian-huginn** [comment]
@Aluxian Sent!
