### ISSUE TITLE
Start minimized.

### ISSUE THREAD

**Issue by chmercesmoreira** [Aluxian/Whatsie#358]
* Operating system: Manjaro Gnome 16.06
* Whatsie version: 2.0.19

Hello, I'd like to suggest an option to start Whatsie minimized in the tray icon, just like Telegram featured here: https://github.com/telegramdesktop/tdesktop/issues/407
They created a cmd parameter called `-startintray` that do this. I'm not asking for an option to start Whatsie on startup, because I can easily do it putting Whatsie in the list of startup applications of my system.

**Comment by Aluxian** [comment]
Hey, that's already possible: App > Run on startup and make sure "start hidden" is checked.

**Comment by chmercesmoreira** [comment]
There's no **Run on startup** option under the App menu:
![image01]
(http://www.auplod.com/u/odalup833e2.png)
Nor a **start hidden** checkbox in any other menu:
![image02]
(http://www.auplod.com/u/loadup833eb.png)
![image03]
(http://www.auplod.com/u/adpolu833e5.png)
![image04]
(http://www.auplod.com/u/alupod833e6.png)
![image05]
(http://www.auplod.com/u/audplo833e7.png)
![image06]
(http://www.auplod.com/u/pualdo833e8.png)

**Comment by chmercesmoreira** [comment]
I'm using the AUR package: https://aur.archlinux.org/packages/whatsie/
That is in the beta release 2.0.19 and have the fixes for the tray icon not appearing: https://github.com/Aluxian/Whatsie/issues/341

If I move to the previous version 2.0.18 from the dev releases I will not be able to use the tray icon until it gets an update to the new version, am I right?
And I will need to do an update manually every time a new update is released beucase the AUR package apparently only get updates for the dev releases.
Can you add a new package on AUR with automatic update for the dev releases?

**Comment by Aluxian** [comment]
> That is in the beta release 2.0.19 and have the fixes for the tray icon not appearing: #341

Ugh, right, I haven't thought about that. Sorry.

> And I will need to do an update manually every time a new update is released because the AUR package apparently only get updates for the dev releases.

AUR and the yum repo get *all* releases – dev, beta and stable.

Please wait until the next update.

**Comment by chmercesmoreira** [comment]
Ok, but as I'm using the last version from AUR that is in the version 2.0.19-beta, I will need to wait the "dev  branch" gets a new update to the same version number? I didn't understand, the dev branch is behind the beta branch?

**Comment by chmercesmoreira** [comment]
Ok, you can close this issue, I'll wait for the update of the dev release.

**Comment by Aluxian** [comment]
It's simple, actually.

This holds true: AUR and the yum repo get all releases – dev, beta and stable.

And versions are always incremental. Thing of dev/beta/stable as tags, not categories – I give one to each version.

Also, the code that shows those 2 menu items about launching on startup is only enabled on -dev. It's still present on every release, it checks if you're on dev before showing up. 


Makes sense?

**Comment by chmercesmoreira** [comment]
Yes, now I understand how this system works, I setup the program to use the dev release channel and now I can see the option to launch on startup, and this option does exactly what I was looking for, the application starts with the system minimized on the tray icon. Thank you.
