### ISSUE TITLE
A new version is available: null

### ISSUE THREAD

**Issue by mzmousa** [Aluxian/Whatsie#359]
* Operating system: Ubuntu 14.04
* Whatsie version: v2.0.15-beta

Download this version of whatsie, set update release channel to `Dev`, then `Download Update`. Also, after pressing `Download`, I get the error 
```JavaScript error in the main process
TypeError: Error processing argument at index 0, conversion failure from null
    at TypeError (native)
    at Function.<anonymous> (/opt/whatsie/resources/app.asar/scripts/browser/managers/auto-update-manager.js:261:29)```

**Comment by Aluxian** [comment]
Please update to the latest version, it's probably been fixed.
