### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by dragons4life** [Aluxian/Whatsie#360]
When the window is resized to a small size the you can only see the avatars, however the problem with this is that you are not able to tell who has message you or your notification numbers.

So why not put the notification numbers on top of the avatars?

**Comment by Aluxian** [comment]
What version are you using?

**Comment by dragons4life** [comment]
I am using the latest, on win 10.

Not sure if I explained what I wanted correctly, sorry.

but basically imagine a number on top of your avatar on github whenever you get a notification.

**Comment by Aluxian** [comment]
I'm asking because I added that in version 2.0.16... not sure why it's not working, I tested it. Just to make sure, latest = 2.0.19?

**Comment by dragons4life** [comment]
Let me re-install than.

**Comment by Aluxian** [comment]
It should look like this, I've just tested:

![pasted_image_26_07_16_14_11](https://cloud.githubusercontent.com/assets/1418870/17135942/1268b1bc-533b-11e6-8033-ebf77ad9cca5.png)

I'll make it green instead of black to be more obvious.

**Comment by dragons4life** [comment]
Yeah I think a color change or a wider amount would be better.

This is how it looks to me.
>img src="http://i.imgur.com/pTniNs7.png"/>

**Comment by Aluxian** [comment]
Yep, I also made it wider. Thanks for the heads up!

**Comment by dragons4life** [comment]
np, thank you for reading my request.
