### ISSUE TITLE
I need two accounts on the same Whatsie program because I...

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Whatsie#366]
**Description:**
I need two accounts on the same Whatsie program because I have a phone with two sim an two Whatsapp accounts.

**Operating system:**
Windows

**Best thing about Whatsie:**
Performance

**Worst thing about Whatsie:**
I can't play any video

**Extra:**
I need a keyboard shortcut for change the spelling languaje

**Comment by Aluxian** [comment]
https://github.com/Aluxian/Whatsie/issues/23
