### ISSUE TITLE
unfortunately the German Spellcheck is not working and it...

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Whatsie#367]
**Description:**
unfortunately the German Spellcheck is not working and it will be nice if you can choose 2 languages at the same time, it is practical when I write to German friends, and than to English friends Thanks :-)

**Steps to reproduce:**
reproduce What?

**App version:**
2.0.19 - beta

**OS:**
Windows 10.1

**Works in WhatsApp Web:**
I haven&#039;t tried

**Extra:**
thanks, it is a great app, location share will be great too, but no worries I know that it's complicated,

**Comment by chmercesmoreira** [comment]
I have a similar issue: https://github.com/Aluxian/Whatsie/issues/363
I think none of the spell check languages are working.

**Comment by Aluxian** [comment]
https://github.com/Aluxian/Whatsie/issues/363
