### ISSUE TITLE
spell check offers no country language options on a windo...

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Whatsie#369]
**Description:**
spell check offers no country language options on a windows 7 home premium laptop

**Steps to reproduce:**
view spell checker language

**App version:**
2014 beta

**OS:**
win7 home premium

**Works in WhatsApp Web:**
I haven&#039;t tried

**Extra:**
allow users to change background images like sephia theme offers

**Comment by Aluxian** [comment]
@aluxian-huginn email op:

```
Please update to the latest version: https://whatsie.chat
```

**Comment by aluxian-huginn** [comment]
@Aluxian Sent!
