### ISSUE TITLE
Drag'n Drop media open the image instead of sending

### ISSUE THREAD

**Issue by Kurobyte** [Aluxian/Whatsie#37]
When I try to send an image to a conversation draggin a image into the window,

First it shows the Whatsapp img sending dialog, but after a second the image shows up at full width.
And you can't go back to the conversation, nor reloading works.
To get Watsie working again you have to restart the aplication.

It's quite annoying. :cry: 

I'm using version 2.0.8

Here a photo of the error:
![2016-04-03_13-48-03](https://cloud.githubusercontent.com/assets/9979616/14232219/d1038572-f9a2-11e5-8e05-5da82768b09a.png)

**Comment by Aluxian** [comment]
Confirmed, I can reproduce it.

**Comment by Aluxian** [comment]
Fixed, will be released in the next version.

**Comment by Aluxian** [comment]
Please update to v2.0.12 and reopen if you still have this issue. Thanks!

**Comment by Kurobyte** [comment]
Now works flawless. Thanks.
