### ISSUE TITLE
How to determine if linux update requires deb or rpm 

### ISSUE THREAD

**Issue by mzmousa** [Aluxian/Whatsie#371]
* Operating system: linux
* Whatsie version: n/a

Hi, I had a somewhat technical question since I'm trying to implement linux updates for my app. I can see that you're using the the value of `distrib` to specify `deb`, `rpm`, etc., but when do you "set" the value of `distrib` in the `package.json`?

The only way I can see this being done is if you build `.deb` and `.rpm` files separately and specify set `distrib` in the `package.json` for each one. I'm using [electron-builder](https://github.com/electron-userland/electron-builder) so I'm just trying to find the optimal way to do this.

**Comment by Aluxian** [comment]
https://github.com/Aluxian/Whatsie/blob/master/tasks/pack.coffee

Ctrl+F and search for `distrib`

**Comment by mzmousa** [comment]
So it looks like you would only need the value of `distrib` to determine whether you require a `deb` or `rpm` file when updating, which is already a part of the `package.json` in the app. That's nice and simple. Thanks for clarifying :smile:
