### ISSUE TITLE
The Gui not appear at first attempt

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Whatsie#375]
**Description:**
The Gui not appear at first attempt

**Steps to reproduce:**
1) Install software on Kubuntu 16.04
2) Run it
3) Reboot PC
4) Run the software... the Gui not appear

**App version:**
2.0.14-Beta

**OS:**
Kubuntu 16.04

**Works in WhatsApp Web:**
Yes

**Extra:**
A optional flag for exclude notification on desktop

**Comment by Aluxian** [comment]
@aluxian-huginn email op:

```
Please update to the latest version: http://whatsie.chat
```

**Comment by aluxian-huginn** [comment]
@Aluxian Sent!
