### ISSUE TITLE
Need a send all button to send message for all contacts i...

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Whatsie#376]
**Description:**
Need a send all button to send message for all contacts in whats app ( Broadcast list have some restriction ) need send all button with out restriction

**Operating system:**
Windows

**Best thing about Whatsie:**
Ease of use

**Worst thing about Whatsie:**
[Not answered]

**Extra:**
[Not answered]

**Comment by Aluxian** [comment]
I can't add this because of how WhatsApp works.
