### ISSUE TITLE
Password protect app on Linux at start up or at x seconds...

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Whatsie#377]
**Description:**
Password protect app on Linux at start up or at x seconds of no use, like Telegram Desktop.

**Operating system:**
Linux

**Best thing about Whatsie:**
Performance, Ease of use

**Worst thing about Whatsie:**
Top Menus, they look like Windows and are not well rendered on Linux

**Extra:**
Nice app!

**Comment by Aluxian** [comment]
Please use a dedicated app for this.
