### ISSUE TITLE
Change category in the Gnome/Mate applications menu from Other to Internet 

### ISSUE THREAD

**Issue by dbogdanov** [Aluxian/Whatsie#38]
I am using Linux Mate. Whatsie appears in Others category, while my other messengers and email applications appear in Internet category.

**Comment by Aluxian** [comment]
This is what `whatsie.desktop` looks like right now:

```
[Desktop Entry]
Name=Whatsie
Comment=A simple &amp; beautiful desktop client for WhatsApp Web.
GenericName=Instant Messenger
Exec=/opt/whatsie/whatsie %U
Icon=whatsie
Terminal=false
Type=Application
StartupNotify=true
StartupWMClass=whatsie
Keywords=WhatsApp;Whats;
Categories=Chat;InstantMessaging;
```

What changes do I need to make in order to move it to the right category?

Could you please paste the `.desktop` file of one of your other apps that appear in Messengers?

**Comment by dbogdanov** [comment]
Here is how ```pidgin.desktop``` looks like:
```
[Desktop Entry]
Name=Pidgin Internet Messenger
GenericName=Internet Messenger
Comment=Chat over IM.  Supports AIM, Google Talk, Jabber/XMPP, MSN, Yahoo and more
Exec=pidgin
Icon=pidgin
StartupNotify=true
Terminal=false
Type=Application
Categories=Network;InstantMessaging;
X-MessagingMenu-UsesChatSection=true
X-MessagingMenu-UsesChatSection=true

X-Ubuntu-Gettext-Domain=pidgin
```

**Comment by Aluxian** [comment]
I changed GenericName to `Internet Messenger` and Categories to `Network;InstantMessaging;`. `2.0.9` is building right now.

**Comment by Aluxian** [comment]
I've just checked on Elementary OS and Whatsie appears under `Internet` so I'm going to assume this has been fixed. Please reopen if you still encounter this issue.

**Comment by dbogdanov** [comment]
Thank you!!
