### ISSUE TITLE
I would prefer the option: minimize to tray instead of sh...

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Whatsie#380]
**Description:**
I would prefer the option: minimize to tray instead of show in tray or both, and also would be cool if you add multilanguage support (for me, ex. german)! :)

**Operating system:**
Windows

**Best thing about Whatsie:**
Performance, Ease of use, Design

**Worst thing about Whatsie:**
Nothing to complain right now ...

**Extra:**
that's all for now.

**Comment by Aluxian** [comment]
https://github.com/Aluxian/Whatsie/issues/248
