### ISSUE TITLE
Close to tray is fine, only multilanguage support would b...

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Whatsie#381]
**Description:**
Close to tray is fine, only multilanguage support would be nice.

**Operating system:**
Windows

**Best thing about Whatsie:**
Performance, Ease of use, Design

**Worst thing about Whatsie:**
nothing.

**Extra:**
nothing more to add ...

**Comment by Aluxian** [comment]
https://github.com/Aluxian/Whatsie/issues/248
