### ISSUE TITLE
i dont have watsapp scan option i my phone what can i do ...

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Whatsie#383]
**Description:**
i dont have watsapp scan option i my phone what can i do now ?

**Steps to reproduce:**
i dont kno

**App version:**
k

**OS:**
ubuntu linux 14

**Works in WhatsApp Web:**
I haven&#039;t tried

**Extra:**
plz help me fast to recover thisissue

**Comment by Aluxian** [comment]
I'm sorry, there's nothing I can do in this case.
