### ISSUE TITLE
Hello, you can setup a Whatsapp account with a Goolge Voi...

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Whatsie#384]
**Description:**
Hello, you can setup a Whatsapp account with a Goolge Voice number. When whatsie tries to reach phone upon installation, and one has the Google Voice phone app installed, it should be able to connect the Google Voice number with Whatsie. It is useful to download The Google Voice app and use it as the phone default number for security. It's VoIP (voice over ip) so it should be encrypted it acts as a phone number proxy, and you can choose an area code of your choice. Google has beefed up Google Voice's voicemail security by allowing PIN numbers greater than 4 characters.

Please make Whatsie work with Google Voice.

**Operating system:**
Linux

**Best thing about Whatsie:**
Performance

**Worst thing about Whatsie:**
No Google Voice compatibility.

**Extra:**

**Comment by Aluxian** [comment]
Sorry, this feature is too complex.
