### ISSUE TITLE
I can't make whatsie not launch when i boot up my pc, the...

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Whatsie#385]
**Description:**
I can't make whatsie not launch when i boot up my pc, the "Launch on start up" button seems pretty much useless in my case

**Steps to reproduce:**
-Install whatsie with the instructions that the whatsie website provides
-Start whatsie
-Uncheck the 'Launch on start up' option
-Restart pc

-It starts and it shouldn't!!

**App version:**
2.0.14-beta

**OS:**
Linux Mint 17.3 Rosa with XFCE4

**Works in WhatsApp Web:**
It&#039;s not relevant for this issue

**Extra:**
Thanks for the service :)

**Comment by jeawrong** [comment]
Same issue on Kubuntu 16.04

**Comment by Aluxian** [comment]
@aluxian-huginn email op:

```
Please update to the latest version: https://whatsie.chat
```

**Comment by aluxian-huginn** [comment]
@Aluxian Sent!
