### ISSUE TITLE
Multiple monitor glitch

### ISSUE THREAD

**Issue by CrisCros01** [Aluxian/Whatsie#386]
* Operating system: WIN10
* Whatsie version: 2.0.19

First of all... great program, thanks. I have whatsie running on my second monitor (Surface Pro 3 + 21 inch monitor). No problems in there, however when I get back to just one monitor, whatsie cannot be reached as is located out limits of the first monitor.

Thanks again and hope feedback helps.

**Comment by levrik** [comment]
@CrisCros01 This is bug of Windows. Also happens often to me for other apps.

**Comment by Aluxian** [comment]
As a workaround, please use Try Menu > Reset.
