### ISSUE TITLE
Tray icon and ability to minimize

### ISSUE THREAD

**Issue by dbogdanov** [Aluxian/Whatsie#39]
The issue is still present on Linux after switching to Whatsie.

Similar issue for Facebook Messenger was [solved](https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/312) in a fork. It would be nice incorporate that back into the original and here.

**Comment by Aluxian** [comment]
Have you tried switching the tray icon on? Enable this: `Menu > App > Show in Tray`

Only on Windows it is enabled by default. Do you think I should I make it on by default for Linux as well? Do messenger apps on Linux have it on by default as well?

I'd also like to get some feedback about the looks of the tray icon (if you get it to work).

**Comment by dbogdanov** [comment]
As soon as I close the application window, the tray icon disappears as well. 

True, I am not sure if it is a good practice to keep tray icon on by default. A good reference would be the Pidgin messenger.

**Comment by Aluxian** [comment]
Okay, I found out why it wasn't working properly and I fixed it. I'll release 2.0.9 including the fix today.

Does Pidgin have the tray icon on by default?

**Comment by dbogdanov** [comment]
I've checked now, it is off by default.

**Comment by Aluxian** [comment]
@dbogdanov I've just published Whatsie 2.0.9, can you please update and check these 2 issues?

**Comment by Aluxian** [comment]
I've just checked, it should be fixed now.
