### ISSUE TITLE
Please use another installer for Windows

### ISSUE THREAD

**Issue by adolfintel** [Aluxian/Whatsie#390]
* Operating system: Windows 10
* Whatsie version: 2.0.19

I've been using Whatsie for a while and it's really good, the only problem I have is with the installer/updater you're using:
-It installs the program to appdata, which is annoying, it should be an option
-When it installs an update it doesn't delete the previous version, wasting ~160MB of space
-When the app is first installed, the downloader doesn't delete the downloaded file, wasting ~60MB in appdata\temp
-When the app is updated, It doesn't delete downloaded package, wasting~60MB of space time the app is updated
-Multiple startup entries are registered for Whatsie and the updater (Only one actually works, but still, it's more trash in the registry)

**Comment by Aluxian** [comment]
The current installed is too deeply integrated into the app so I'm not willing to change it. It keeps the last and the second to last app folders, so only the older ones are deleted.
