### ISSUE TITLE
If phone camera is not working, how i use WhatsApp web app?

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Whatsie#392]
**Description:**
If phone camera is not working, how i use WhatsApp web app?

**Operating system:**
Windows

**Best thing about Whatsie:**
Other_ Modification

**Worst thing about Whatsie:**
need to way to use without scan QR

**Extra:**
Just nothing. above are the only

**Comment by Aluxian** [comment]
Unfortunately, you can't, sorry.
