### ISSUE TITLE
The tray icon on Ubuntu 16.04 could have a higher resolut...

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Whatsie#398]
**Description:**
The tray icon on Ubuntu 16.04 could have a higher resolution, I think. I am on a FHD screen and it looks  pixelated.

**Operating system:**
Linux

**Best thing about Whatsie:**
Nothing

**Worst thing about Whatsie:**
Themes other than default are really ugly.

**Extra:**
[Not answered]

**Comment by Aluxian** [comment]
https://github.com/Aluxian/Whatsie/issues/109
