### ISSUE TITLE
Add an option when you can minimize the app in the notifi...

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Whatsie#399]
**Description:**
Add an option when you can minimize the app in the notification area.

**Operating system:**
Linux

**Best thing about Whatsie:**
Ease of use, Design

**Worst thing about Whatsie:**
Slow time when it starts. Not so much on Linux (Arch 64bit), but definately on Windows (Win7 64bit).

**Extra:**
Great app and I can the potential on this project. Keep up the good work! :)
And of course, thank you for your app :)

**Comment by Aluxian** [comment]
This has been added already, please check the menu.
