### ISSUE TITLE
There's a visual bug with the chatbox and general message...

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Whatsie#401]
**Description:**
There's a visual bug with the chatbox and general message box where the small tick and some other visual elements do not properly match the theme

**Steps to reproduce:**
1.- Open Whatsie
2.- Load a conversation
3.- Choose any "dark"/non-clear theme

**App version:**
Version 2.0.19-beta

**OS:**
Windows 10 Pro x86_64

**Works in WhatsApp Web:**
Yes

**Extra:**
Sorry for reporting this as an issue/bug-- I just wanted to give a heads up that this is happening, not really being "needed" to be fixed. Just a reminder/notice

**Comment by Aluxian** [comment]
https://github.com/Aluxian/Whatsie/issues/19
