### ISSUE TITLE
Multiple SELECT for Delete function.

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Whatsie#405]
**Description:**
Multiple SELECT for Delete function.

**Operating system:**
Windows, Linux

**Best thing about Whatsie:**
Performance, Ease of use

**Worst thing about Whatsie:**
Can only delete single items.

**Extra:**
Add : Download of pictures from Contact Info pop-up.

**Comment by levrik** [comment]
@Aluxian I think the download of profile pictures should be possible to do. I will submit a PR if you're okay with that.
