### ISSUE TITLE
Custom theme builder

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Whatsie#409]
**Description:**
Custom theme builder

**Operating system:**
OS X, Windows, Linux

**Best thing about Whatsie:**
Performance, Ease of use, Design

**Worst thing about Whatsie:**
Would be nice for it to have an option for no taskbar segment (Linux) and just have a tray icon. Then again I could just be being a noob!

**Extra:**
I suggested a theme builder because I think once the app is stable and more and more people download it, some people may want an easy way to customise the look of Whatsie outside of the built in themes. It's quite trivial I suppose and nothing of major importance and tbh I don't care either way if it's there, the dark theme suits me nicely but I think some people may appreciate it. :)

**Comment by Aluxian** [comment]
https://github.com/Aluxian/Whatsie/issues/124
