### ISSUE TITLE
Linux: no tray icon, not closing to the tray

### ISSUE THREAD

**Issue by arekbulski** [Aluxian/Whatsie#410]
On Ubuntu and probably other Linuxes, Whatsies does not show an icon in systray (its called differently but anyway). Also when closing window, it should minimize to the tray as well. Thirdly, it could change the icon when unread messages are awaiting.

**Comment by chmercesmoreira** [comment]
You need to switch to the dev release channel:
![whatsie](https://cloud.githubusercontent.com/assets/20016536/17973800/32dc5afc-6aba-11e6-8883-d591a37cb53a.png)
After doing it you will see the options to start/minimize on the system tray and to startup with the system.

**Comment by arekbulski** [comment]
Thank you.
