### ISSUE TITLE
Spell checker not working

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Whatsie#413]
**Description:**
Dictionary doesn't suggest anything when misspeel a word. I'm using Spanish language.

**Steps to reproduce:**
Type anything wrong in individual or group window.

**App version:**
2.0.19-beta

**OS:**
Windows 10

**Works in WhatsApp Web:**
Yes

**Extra:**
[Not answered]

**Comment by Aluxian** [comment]
https://github.com/Aluxian/Whatsie/issues/363
