### ISSUE TITLE
High level: Whatsie busts my eardrums with its notificati...

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Whatsie#415]
**Description:**
High level: Whatsie busts my eardrums with its notification when I am listening to music through sensitive headphones.

What I have tried: I turned off notification sounds in OS X System prefs (Sound), as well as disabled whatsie in the notifications centre prefs.

**Steps to reproduce:**
Listen to a (soft) song on loud volume. Turn off/turn down all OS X notifications using Prefs->Sound. Use notifications panel to turn off Whatsie sounds. Receive a whatsapp_ message and Whatsie will do a number on your eardrum.

**App version:**
Version 2.0.19-beta (2.0.19.219) -- latest version

**OS:**
OSX 10.10.5

**Works in WhatsApp Web:**
It&#039;s not relevant for this issue

**Extra:**
lovely feedback form

**Comment by Aluxian** [comment]
Should get fixed when this is implemented: https://github.com/Aluxian/Whatsie/issues/68
