### ISSUE TITLE
Hello. In the Whatsie: toggle left aside section with cha...

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Whatsie#418]
**Description:**
Hello. In the Whatsie: toggle left aside section with chat selection. Also some themes need to be improved.

**Operating system:**
Linux

**Best thing about Whatsie:**
Ease of use

**Worst thing about Whatsie:**
Themes, it's like some colors are missed.

**Extra:**
Thank you

**Comment by Aluxian** [comment]
You'll be able to toggle the sidebar in the next version.

https://github.com/Aluxian/Whatsie/issues/19
