### ISSUE TITLE
PUA detected by windows defender

### ISSUE THREAD

**Issue by lukigno95** [Aluxian/Whatsie#419]
* Operating system: Windows 10 build 14393
* Whatsie version: I don't know

When I download whatsie from the official site windows defender blocks it.
![image](https://cloud.githubusercontent.com/assets/8702173/18011333/fc19c724-6bb4-11e6-9c81-53bddb3807ca.png)

I have activated anti PUA on windows defender

**Comment by Aluxian** [comment]
That's because I added an optional step in the installer that allows users to install extra apps. As I said, completely optional, no harm.
