### ISSUE TITLE
Error: nothing provides libappindicator1 needed by whatsie-2.0.9-313.x86_64

### ISSUE THREAD

**Issue by rbieb** [Aluxian/Whatsie#42]
Error happens on fedora 23.

Whatsie is looking for the libappindicator1 package, which doesn't exist on fedora. Available packages are libappindicator and libappindicator-gtk3.

Please replace the dependency on libappindicator1 with a dependency on one of these two packages.

**Comment by Aluxian** [comment]
Thanks, I think I will update the requirement to `libappindicator1 OR libappindicator OR libappindicator-gtk3`. This should be the safest bet, right? Now, how do I do this with rpm... I've done a quick search on Google and users say this `a OR b OR c` use case is handled by a, b and c declaring a virtual package on which my app would depend on. I'll see if `libappindicator` et al. provide a virtual package. Any other suggestions to solve this would be great.

**Comment by Aluxian** [comment]
What's the difference between `libappindicator` and `libappindicator-gtk3`? How should I know which one my app needs? Does this depend on the distro?

**Comment by rbieb** [comment]
I have no idea. I guess your first idea with OR should be the best bet, I'd just try that first and then we'll sell in anyone still has issues.

**Comment by Aluxian** [comment]
RPM packages don't have OR dependencies. This case is solved by dependencies providing a common, virtual package on which the dependent (my app) would eventually depend on. But I don't know what that virtual package is or even if they provide one.

**Comment by Aluxian** [comment]
Actually, that's possible: http://www.rpm.org/wiki/PackagerDocs/BooleanDependencies

**Comment by Aluxian** [comment]
@rbieb does it matter which rpm version I use to build the package? For example, if I use rpm-4.13 to build the package, will users with older rpm versions still be able to install the app?

I don't think they would since 4.13 brings changes to the spec that older versions wouldn't know how to read. But it's just my guess so I'm really not sure.

**Comment by Aluxian** [comment]
I don't know how to install rpm-4.13 on Circle CI (Ubuntu), so the only change I made is that the rpm package now depends on `libappindicator`.

@rbieb Does `2.0.11` work?

**Comment by rbieb** [comment]
Installation works great now, I get an error when trying to run it though. Do you want me to open a new issue for it?

https://paste.ee/p/SpWo1#

**Comment by Aluxian** [comment]
Yes, please.

--
Alexandru Rosianu Full-Stack Developer aluxian.com | startersquad.com On Fri, Apr 15, 2016 at 7:11 PM, rbieb < notifications@github.com [notifications@github.com] > wrote:
Installation works great now, I get an error when trying to run it though. Do you want me to open a new issue for it?

https://paste.ee/p/SpWo1# [https://paste.ee/p/SpWo1]
