### ISSUE TITLE
In the window menu tab a feature to show/hide contacts. T...

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Whatsie#421]
**Description:**
In the window menu tab a feature to show/hide contacts. This will allow a frame to be even smaller so that only the chat shows, so that I have more space on my screen while the program is always on top

**Operating system:**
Linux

**Best thing about Whatsie:**
Ease of use, Design

**Worst thing about Whatsie:**
Stil a little big on laptop screen

**Extra:**
Auto hide the frame when inactive for example 10 seconds and when a new message comes in the frame is shown again, but no focus is gained to the frame

**Comment by Aluxian** [comment]
Too complex.
