### ISSUE TITLE
My laptop camera is not synchronized while taking a selfi...

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Whatsie#422]
**Description:**
My laptop camera is not synchronized while taking a selfie (as attachment)!

**Steps to reproduce:**
don't know

**App version:**
2.0.14(beta)

**OS:**
Windows 10

**Works in WhatsApp Web:**
No

**Extra:**
It is better than the Official WhatsApp. Great job!

**Comment by Aluxian** [comment]
Please try the latest version. Other than that, I can't help.
