### ISSUE TITLE
When the software is closed and the icon is in tray, I ca...

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Whatsie#425]
**Description:**
When the software is closed and the icon is in tray, I can't open the Whatsie with double-click.

**Steps to reproduce:**
Enable to show Whatsie in tray;
Closed Whatsie windows;
Try open the software with double-clicks

**App version:**
2.0.14 beta

**OS:**
Debian Jessie

**Works in WhatsApp Web:**
Yes

**Extra:**
[Not answered]

**Comment by Aluxian** [comment]
@aluxian-huginn email op:

```
Please update to the latest version: https://whatsie.chat
```

**Comment by aluxian-huginn** [comment]
@Aluxian Sent!
