### ISSUE TITLE
Use the "append" hint in linux notifications

### ISSUE THREAD

**Issue by 3v1n0** [Aluxian/Whatsie#43]
When supported (mostly Ubuntu's notifyOSD), this would allow to merge messages coming from the same origin into a single bubble.

Check [this](https://wiki.ubuntu.com/NotifyOSD#Merging_notifications) and [dev info](https://wiki.ubuntu.com/NotificationDevelopmentGuidelines#How_to_use_the_append-hint).

**Comment by Aluxian** [comment]
But this is something that [Electron](https://github.com/electron/electron) should implement, right? Electron handles notifications on Linux, not Whatsie directly.

**Comment by 3v1n0** [comment]
Sure, reported there as well: https://github.com/electron/electron/issues/5052

**Comment by Aluxian** [comment]
Awesome! I was going to do it, but I asked first to be sure :) Thanks

**Comment by 3v1n0** [comment]
There should be still something to do at Whatsie level whenever Electron will support this, though (as I guess it's a tunable thing)

**Comment by Aluxian** [comment]
I don't think so. WhatsApp Web sends notifications with the contact's name as the title, so notify-osd should work as you wanted (and like on OS X): notifications with the same title but different message are merged.

**Comment by 3v1n0** [comment]
Well, that depends in how Electron wants to handle that.

In case they'll add a flag (which should be probably better, as it's something
not expected in default case), then you need to change the Whatsie code as
well.

> On apr 6 2016, at 2:34 pm, Alexandru Rosianu
&lt;notifications@github.com&gt; wrote:  

>

> I don't think so. WhatsApp Web sends notifications with the contact's name
as the title, so notify-osd should work as you wanted (and like on OS X):
notifications with the same title but different message are merged.

>

> —  
You are receiving this because you authored the thread.  
Reply to this email directly or [view it on GitHub](https://github.com/Aluxian
/Whatsie/issues/43#issuecomment-206350492)![](https://github.com/notifications
/beacon/AAVGS_uVApHiczJaEWoRcAT1hMTpSX4Rks5p06hIgaJpZM4IAOvK.gif)

**Comment by Aluxian** [comment]
I don't think they should add a flag, but these are just opinions. You're right.

**Comment by Aluxian** [comment]
Added upstream and in https://github.com/Aluxian/Whatsie/releases/tag/v2.0.14

@3v1n0 Can you please test and report back?

**Comment by 3v1n0** [comment]
So, I'm running this, but they don't seem to merge here. Although this should be default in electron `0.37.6`. Weird.

**Comment by Aluxian** [comment]
Maybe WhatsApp Web sends unique tags with the notifications? I'll verify this assumption.

**Comment by 3v1n0** [comment]
No, I've just checked by doing new notifications by hand through the inspector.

It looks like that the released v0.37.6, doesn't really include this. If I compile that electron revision, it works, but not using the pre-compiled binary. I guess we'll have to wait 0.37.7.

**Comment by Aluxian** [comment]
WhatsApp does include a tag, but it's an ID (e.g. 00000@c.us) and it's the same for every message from the same contact. So this is not the problem, as you figured out.

**Comment by Aluxian** [comment]
This should be live in the latest update (2.0.15). @3v1n0 Can you please test again? Thanks!
