### ISSUE TITLE
I think it would be great to add the Emojis Shortcut like...

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Whatsie#432]
**Description:**
I think it would be great to add the Emojis Shortcut like in telegram desktop (its really annoying to click on every single emoji to send :P)

**Operating system:**
Linux

**Best thing about Whatsie:**
Performance, Ease of use, Design

**Worst thing about Whatsie:**
Disconnects when cell phone is offline

**Extra:**
Great job with the app :D

**Comment by Aluxian** [comment]
https://github.com/Aluxian/Whatsie/issues/32
