### ISSUE TITLE
when adding photos to group chat, screen goes black and n...

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Whatsie#434]
**Description:**
when adding photos to group chat, screen goes black and need to reload whatsie again. Photos make screen go black each time.

**Steps to reproduce:**
drag a photo or attatch photos in a group chat and click ok.

**App version:**
2.0.19-beta

**OS:**
windows 10

**Works in WhatsApp Web:**
I haven&#039;t tried

**Extra:**
no.

**Comment by Aluxian** [comment]
https://github.com/Aluxian/Whatsie/issues/361
