### ISSUE TITLE
java script error in the main process http://imgur.com/Vd...

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Whatsie#440]
**Description:**
java script error in the main process http://imgur.com/VdxomQA

**Steps to reproduce:**
nothing, just let the app open and that error message just appear

**App version:**
2.0.16-dev

**OS:**
win10 64

**Works in WhatsApp Web:**
Yes

**Extra:**
[Not answered]

**Comment by Aluxian** [comment]
@aluxian-huginn email op:

```
Please download the latest version from: https://whatsie.chat/
```

**Comment by aluxian-huginn** [comment]
@Aluxian Sent!
