### ISSUE TITLE
It would be nice to have a "Minimize with Escape Key" option

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Whatsie#443]
**Description:**
It would be nice to have a "Minimize with Escape Key" option

**Operating system:**
Linux

**Best thing about Whatsie:**
Ease of use

**Worst thing about Whatsie:**
Hmm... Just started to use it. Have nothing to say... yet :)

**Extra:**
Nope :)

**Comment by Aluxian** [comment]
Please check the menu
