### ISSUE TITLE
[production][] The request timed out.: (null)

### ISSUE THREAD

**Issue by Aluxian** [Aluxian/Whatsie#45]
[See this exception on Errbit](https://exceptions.whatsie.chat/apps/56eff7bd64da236b41000003/problems/5702927f64da231acf000e34)
# The request timed out.: (null) #
### URL ###
[app:///scripts/browser/managers/auto-update-manager.js](app:///scripts/browser/managers/auto-update-manager.js)"
### Occured ###
Apr 04  7:12pm

### Similar ###
10

## Params ##
~~~
{}
~~~

## Session ##
~~~
{
  &quot;app_version&quot; =&gt; &quot;2.0.8&quot;,
  &quot;distrib&quot; =&gt; &quot;darwin64:dmg&quot;,
  &quot;electron_version&quot; =&gt; &quot;v0.37.3&quot;,
  &quot;process_type&quot; =&gt; &quot;browser&quot;,
  &quot;raw_stack&quot; =&gt; [&quot;Error: The request timed out.: (null)&quot;, &quot;    at Error (native)&quot;]
}
~~~

## Backtrace ##
~~~
:   -> **Error**
~~~

## Environment ##
| Key        | Value      |
|------------|------------|
| err&amp;#46;sender | {&quot;_events&quot;=&gt;{&quot;error&quot;=&gt;[nil, nil, nil], &quot;checking-for-update&quot;=&gt;[nil, nil], &quot;update-available&quot;=&gt;[nil, nil, nil], &quot;update-not-available&quot;=&gt;[nil, nil], &quot;update-downloaded&quot;=&gt;[nil, nil]}, &quot;_eventsCount&quot;=&gt;5} |
| process&amp;#46;pid | 641 |
| process&amp;#46;uid | 501 |
| process&amp;#46;gid | 20 |
| process&amp;#46;cwd | / |
| process&amp;#46;execPath | /Applications/Whatsie.app/Contents/MacOS/Whatsie |
| process&amp;#46;version | v5.1.1 |
| process&amp;#46;argv | [&quot;/Applications/Whatsie.app/Contents/MacOS/Whatsie&quot;] |
| process&amp;#46;memoryUsage | {&quot;rss&quot;=&gt;103464960, &quot;heapTotal&quot;=&gt;35487744, &quot;heapUsed&quot;=&gt;28084216} |
| os&amp;#46;loadavg | [1.01171875, 1.1279296875, 1.14599609375] |
| os&amp;#46;uptime | 157107 |
| HTTP_USER_AGENT |  |

**Comment by govi2010** [comment]
I am facing same error. Did you fix this ?
