### ISSUE TITLE
64 bit builds missing?

### ISSUE THREAD

**Issue by beppe9000** [Aluxian/Whatsie#46]
is it me or it is missing?

**Comment by Aluxian** [comment]
For Windows? It's just not being built. I don't see a reason to have both 32 bit and 64 bit releases for Windows. However, I'm not 100% sure of the advantages of having 64 bit builds. I decided not to build for 64 bit just because Whatsie is such a small app and there wouldn't be any noticeable performance improvements.

If someone could contradict me or give more insight, that'd be great.

**Comment by beppe9000** [comment]
If it only means changing a flag... Well, why not? JavaScript itself is platform-agnostic so I don't think you would have to do much work...  Being native sure sounds like an advantage to me: you get appropriate optimizations for the selected architecture. 32-bit applications on 64-bit windows systems run on WOW64, an emulation layer, that means increased ram consumption (not a lot tough) and registry key redirection, that may be bad for users when diagnosing problems (if you use the registry in some way). I think that putting 32-bit nw.exe and the 64-bit one in the same folder and use a common package would be practical.

**Comment by Aluxian** [comment]
But would those optimizations bring a noticeable performance increase? Is 64-bit Chrome really faster than the 32-bit version? I only use the registry to set the app to launch on startup.

Whatsie is built with Electron, not nwjs. Supporting 64-bit would mean having a separate installer and portable zip. Writing one more task to do that wouldn't take so long, but I'd rather keep things simple.

**Comment by beppe9000** [comment]
http://blog.chromium.org/2014/08/64-bits-of-awesome-64-bit-windows_26.html
In my opinion things remain simple as long as the code is the same...

**Comment by Aluxian** [comment]
Okay, it might bring some improvements, so I'll leave this open. Although I prefer to keep things simple, I might add a 64-bit build in the future (although anyone can help with this right now).

**Comment by Aluxian** [comment]
I'm going to close this because, as I said, it's not worth it shipping both 32- and 64-bit builds. Thanks for the suggestion.
