### ISSUE TITLE
Application being closed when press [Alt+F4]

### ISSUE THREAD

**Issue by eliasjnior** [Aluxian/Whatsie#47]
I noticed that when we press the X button, the app is minimised. That's the right thing in my opinion. But, I usually press Alt+F4, and it's really close the aplication. Would be better if this hotkey works like the X button, minimising the app.

**Comment by Aluxian** [comment]
I'm thinking I should make Alt-F4 just close the window and add an Exit item in the App menu and a Ctrl+Q keyboard shortcut to quit entirely.

**Comment by Aluxian** [comment]
Please update to v2.0.12 and reopen if you still have this issue. Thanks!
