### ISSUE TITLE
[Windows] Desktop Notifications aren't shown

### ISSUE THREAD

**Issue by AdrianoCahete** [Aluxian/Whatsie#48]
Windows 10 x64

When anyone send me a message, i hear the sound, but notifications toaster didn't appear.

Notification is enabled in Whatsie/WhatsApp.
No option appears in "Windows Notify options":
![whatsie_notify](https://cloud.githubusercontent.com/assets/37474/14364276/7606affc-fcde-11e5-9b41-59269ac60f11.PNG)

**Comment by Aluxian** [comment]
Thanks, now this explains another report that I've received about notifications not showing. I'll look into it.

**Comment by AdrianoCahete** [comment]
Just an update: Whatsie now appears on Notification Center, but notification toaster still don't work.

**Comment by Aluxian** [comment]
The notifications should be fixed in https://github.com/Aluxian/Whatsie/releases/tag/v2.0.14. Can anyone please test and report back?

**Comment by AdrianoCahete** [comment]
Fixed! :)
