### ISSUE TITLE
[Linux] [Windows] Unread messages count

### ISSUE THREAD

**Issue by Martin-Oehler** [Aluxian/Whatsie#49]
**Platform:** Windows

It would be nice to have an indicator for unread messages at the tray symbol in case you miss the notification.
Currently you have to check Whatsapp every time you return to your PC, because there is no easy way to tell, if you missed a message.

**Comment by Aluxian** [comment]
Well, here's another bug... The tray icon is supposed to change color to green when there's a notification.

**Comment by Martin-Oehler** [comment]
What exactly is supposed to change to green? The three dots in the middle? If yes, it's barely noticeable.

**Comment by Aluxian** [comment]
Ah, so it works! Good. Thanks for the feedback.

I'll probably make it green. Can you please take a screenshot/photo of the tray icon with the green dots so I can see how it looks? Also, one with Skype if you can (my main machine is a Mac, that's why it's harder for me to do it myself).

**Comment by Martin-Oehler** [comment]
From left to right:
Unread message, normal, Skype with one unread message

![whatsie](https://cloud.githubusercontent.com/assets/7110154/14470255/bd0f14bc-00e8-11e6-8a31-f47a1619d374.png)

**Comment by Aluxian** [comment]
How is https://github.com/Aluxian/Whatsie/releases/tag/v2.0.14? Is the tray icon more noticeable now?

**Comment by Martin-Oehler** [comment]
It is a huge improvement, thank you. Unless you want to add a count for unread messages, we can close this now.

**Comment by Aluxian** [comment]
Adding a count would require either editing the tray icon or shipping several tray icons with the numbers already on them, I'll keep this open as an enhancement.

**Comment by Aluxian** [comment]
I added a badge to the icon (shown in taskbar, not tray) on Windows and Linux too.

Check for update inside the app or download Whatsie again from https://github.com/Aluxian/Whatsie/releases/tag/v2.0.18

**Comment by Martin-Oehler** [comment]
Very nice update, I really like it. Thank you!
