### ISSUE TITLE
Offline support?

### ISSUE THREAD

**Issue by orschiro** [Aluxian/Whatsie#50]
Dear @Aluxian,

Is it possible to add some kind of offline support, e.g. to have access to most recent conversations while offline or prepare posts while offline?

Thankfully,

~Robert

**Comment by Aluxian** [comment]
WhatsApp Web does have some support for offline mode, but it's very limited afaik.

Adding support for viewing past conversations while offline would require a lot of work with reading data, caching, and then recreating the list of messages by integrating/injecting some of my code into WhatsApp Web.

That's too complicated and something I'm not willing to do, sorry.

**Comment by orschiro** [comment]
Dear Alexandru,

  

Totally understandable.

  

Thank you still for sharing your perspective on this request!

  

Warmly,

  

~Robert

  
Sent from [Nylas N1](https://nylas.com/n1?ref=n1), the extensible, open source
mail client.  

On Apr 12 2016, at 12:38 pm, Alexandru Rosianu
&lt;notifications@github.com&gt; wrote:  

> Closed [#50](https://github.com/Aluxian/Whatsie/issues/50).

>

> —  
You are receiving this because you authored the thread.  
Reply to this email directly or [view it on GitHub](https://github.com/Aluxian
/Whatsie/issues/50#event-623917313)![](https://github.com/notifications/beacon
/AAKbw1wghnklkLEy43SBVudsGlS_ED9Oks5p23YtgaJpZM4IDNNl.gif)

**Comment by Aluxian** [comment]
Your messages/emails are very elegant and respectful. I appreciate that, it's not something you see every day. Just my thought of appreciation, keep it up :)

**Comment by orschiro** [comment]
Dear Alexandru,

  

I thank you for your kind and warm words!

  

For me taking time for composing is one of the foundations for how I want to
collaborate beautiful things in a respectful way. :-)

  

Let's keep in touch,

  

~Robert

  
Sent from [Nylas N1](https://nylas.com/n1?ref=n1), the extensible, open source
mail client.  

On Apr 12 2016, at 6:56 pm, Alexandru Rosianu &lt;notifications@github.com&gt;
wrote:  

> Your messages/emails are very elegant and respectful. I appreciate that,
it's not something you see every day. Just my thought of appreciation, keep it
up :)

>

> —  
You are receiving this because you authored the thread.  
Reply to this email directly or [view it on GitHub](https://github.com/Aluxian
/Whatsie/issues/50#issuecomment-209006219)![](https://github.com/notifications
/beacon/AAKbw2rYWGgFAwEBR4UYRpjAAHGNWpKMks5p287YgaJpZM4IDNNl.gif)
