### ISSUE TITLE
[Linux Mint 17.3] Can't start Whatsie

### ISSUE THREAD

**Issue by pietrochico** [Aluxian/Whatsie#53]
Downloaded and installed .deb. Can't start Whatsie, even from command line.  Currently on Linux Mint  17.3 64 bit.

**Comment by Aluxian** [comment]
It's time to debug this, then! Please run this in your terminal and paste here the output:

```
export DEBUG="whatsie:*"
whatsie
```

**Comment by pietrochico** [comment]
Waiting for a response, I tried the old one "Remove and reinstall" and now it's working flawlessly!
Thanks a lot for the quick response!

**Comment by Aluxian** [comment]
Great! What exactly did you do?

**Comment by pietrochico** [comment]
Simply sudo apt-get remove and --purge remove whatsie. Then, re-downloaded the .deb file and reinstalled everything.

**Comment by Aluxian** [comment]
:+1:
