### ISSUE TITLE
Spell Checker Language empty

### ISSUE THREAD

**Issue by simonbcn** [Aluxian/Whatsie#56]
Arch Linux 64 bits
Installed from AUR: https://aur.archlinux.org/packages/whatsie/

It doesn't show any dictionary:
![consejo emergente_001](https://cloud.githubusercontent.com/assets/428231/14525805/95bf0b08-023f-11e6-8516-abbcd9ca8e35.png)

How can I add a Spanish language?

**Comment by mrl4214** [comment]
@Aluxian what is the dependency for spell checker?

**Comment by Aluxian** [comment]
Whatsie uses [node-spellchecker](https://github.com/atom/node-spellchecker): *Native bindings to NSSpellChecker, Hunspell, or the Windows 8 Spell Check API, depending on your platform. Windows 7 and below as well as Linux will rely on Hunspell.*

**Comment by Aluxian** [comment]
The app should have **at least** en-US on Linux, I don't know why that returns empty. Can you please open the dev tools (`Ctrl+I`) and paste the following there:

```
require('spellchecker').getAvailableDictionaries()
```

What does it print?

**Comment by mrl4214** [comment]
@simonbcn try installing https://www.archlinux.org/packages/extra/i686/hunspell/ and let me know if that works. I can add it as a dependency if that's the case...

**Comment by simonbcn** [comment]
I have installed `hunspell`:
```
local/hunspell 1.3.4-1
    Spell checker and morphological analyzer library and program
local/hunspell-es 1:2.0-1
    Spanish hunspell dictionaries
```
@Aluxian where I open the dev tools? In Whatsie? It doesn't work.

**Comment by simonbcn** [comment]
I have executed in console:
```
$ node
> require('spellchecker').getAvailableDictionaries()
Error: Cannot find module 'spellchecker'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at repl:1:1
    at REPLServer.defaultEval (repl.js:269:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:439:12)
    at emitOne (events.js:95:20)
```

**Comment by Aluxian** [comment]
You need to be *inside* Whatsie. Focus the app window, then press `Ctrl+I` or click `View > Toggle Developer Tools`. Once Developer Tools is opened, switch to the tab `console` and paste that command there.

**Comment by simonbcn** [comment]
@Aluxian it didn't work because in my Whatsie the shortcut is `Alt+Ctrl+I` (_I've seen it now_ :eyes: ).

In console I see several errors:
```
Failed to load resource: net::ERR_CONNECTION_REFUSED
WV: Creating Application Cache with manifest https://web.whatsapp.com/404.appcache
WV: Application Cache Checking event
WV: Application Cache Error event: Manifest fetch failed (404) https://web.whatsapp.com/404.appcache
```
It returns an empty list:
```
> require('spellchecker').getAvailableDictionaries()
[]
```

**Comment by Aluxian** [comment]
My bad about the shortcut :eyes: 

Those errors/messages are normal. If spellchecker returns an empty array, then it's probably spellchecker's fault here...

**Comment by Aluxian** [comment]
I'll update spellchecker in the next release.

**Comment by Aluxian** [comment]
Any chance this works in v2.0.12 now? I updated spellchecker, but I don't think it fixed anything... (I looked at the commits)

**Comment by simonbcn** [comment]
It still fails. :cry:

**Comment by mrl4214** [comment]
Solved in build 2.0.13!

**Comment by Aluxian** [comment]
Yeah! So, if you want additional languages, just install hunspell and the correponding hunspell-* package (e.g. hunspell-es).

**Comment by simonbcn** [comment]
Thanks :smiley:

**Comment by h0wdyd3wdy** [comment]
I just installed 2.0.15 beta and there are no dictionaries listed, but I have these installed:

hunspell-en-US-0.20140811.1-2.fc23.noarch
hunspell-1.3.3-8.fc23.i686
hunspell-en-0.20140811.1-2.fc23.noarch
hunspell-ar-3.5-2.fc23.noarch
hunspell-1.3.3-8.fc23.x86_64
hunspell-en-GB-0.20140811.1-2.fc23.noarch

whatsie-2.0.15-467.x86_64

**Comment by simonbcn** [comment]
Works for me on Arch Linux:
```
hunspell 1.3.4-1
hunspell-es 1:2.0-1
```

**Comment by Aluxian** [comment]
My guess is that @h0wdyd3wdy's dictionaries are someplace else than `/usr/share/hunspell`... I asked him on Gitter to show me the output of this:

```
ls -al /usr/share/hunspell
```

**Comment by simonbcn** [comment]
IMHO, it would be better to talk about the issue in this same thread. This way, the entire conversation is maintained in one location. If someone has the same issue, it may see the problem and potential solution here.
