### ISSUE TITLE
Add build step to publish to AUR / Arch Linux

### ISSUE THREAD

**Issue by Aluxian** [Aluxian/Whatsie#60]
I'd like to integrate building and publishing to AUR into the CI build script ([this file](https://github.com/Aluxian/Whatsie/blob/master/circle.yml)).

This is what we'd have to do:

- [ ] add a task in `tasks/pack.coffee` to create the AUR package
- [ ] add a task in `tasks/publish.coffee` to upload the package to https://aur.archlinux.org/packages/
- [ ] add the commands to `circle.yml` to run the tasks defined above

OR, on second thought (I'm just learning about AUR):

- [ ] add a task in `tasks/publish.coffee` to submit to AUR a script that converts the DEB package to AUR format
- [ ] add the commands to `circle.yml` to run the tasks defined above

The idea started with this PR: https://github.com/Aluxian/Whatsie/pull/55

---

- [ ] Also fix this: https://github.com/Aluxian/Whatsie/issues/270

**Comment by simonbcn** [comment]
I think I can help you in this. It's very easy. Right now I can't but I'll explain later.

**Comment by Aluxian** [comment]
Awesome! Just a note:

I think we don't have to build the package for AUR ourselves, we can create a script to convert the .deb we already build to AUR's format. If you want to collaborate on this feature, we can get in touch [on Gitter](https://gitter.im/Aluxian/Whatsie).

**Comment by Aluxian** [comment]
To keep in mind: https://huboard.com/Aluxian/Whatsie#/issues/150425484

**Comment by Aluxian** [comment]
@simonbcn I did this, can you please install it (`yaourt -S whatsie`) and make sure everything's alright?
