### ISSUE TITLE
[Linux] .config/Whatsie/prefs.json cannot be found

### ISSUE THREAD

**Issue by rbieb** [Aluxian/Whatsie#67]
https://paste.ee/p/SpWo1#

Error happens when trying to run the program on fedora 23.

**Comment by mlopezgva** [comment]
Linux Mint Cinnamon 17.3 amd64 when installed using the repository (deb://). Installing it from the `.deb` package is less... faulty:

![image](https://cloud.githubusercontent.com/assets/996070/14568750/3bc7d706-0311-11e6-82ee-7de9c5fc637e.png)

**Comment by Aluxian** [comment]
v2.0.12 is building right now, please update when it becomes available.
