### ISSUE TITLE
[Windows] Auto update break shortcuts and notification options

### ISSUE THREAD

**Issue by AdrianoCahete** [Aluxian/Whatsie#69]
In Windows, at least.

Auto update don't rewrite/update actual files or remove the previous version (it's a little problem if you have a small SSD) , but create a new folder with new app version. 
So, shortcuts still point to previous version (or version who is newer when you create the shortcut).

And how executable is newer (and in other folder), Windows (10 here) sees as other program, and don't use notify preferences already choosen. (a lot of Whatsies options)
![whatsie_update_bug](https://cloud.githubusercontent.com/assets/37474/14582324/fb1e2d28-03d7-11e6-8c54-5984079129ac.PNG)

**Comment by Aluxian** [comment]
What does the folder `C:\Users\<your user name>\AppData\Local\whatsie` contain on your machine?
Please do a restart, are the older apps removed? Are the entries in settings fixed?

**Comment by AdrianoCahete** [comment]
> What does the folder C:\Users\<your user name>\AppData\Local\whatsie contain on your machine?

I removed folder by myself, but i see a lot of "app-2.0.XX" (where XX is version, 10, 11, 12). In the next update, i take a screenshot.

> Please do a restart, are the older apps removed?
I don't think so. I don't restart too much (in fact, almost never), I'll try the next update.

> Are the entries in settings fixed?

This is certain: No. That Whatsies versions are from other installations. I have something like 2 more entries here. And always need to manually change to active, to show on windows Taskbar.

**Comment by Kurobyte** [comment]
For the shortcuts it's easy to fix change the shorcut to this:
Destiny: `C:\Users\<your user>\AppData\Local\whatsie\Update.exe --processStart Whatsie.exe`
and Starts in: `C:\Users\<your user>\AppData\Local\whatsie`

With this Whatsie will start allways in the latest version without touching the shortcut.
Works for me in Win 7.

**Comment by AdrianoCahete** [comment]
> With this Whatsie will start allways in the latest version without touching the shortcut.
Works for me in Win 7.

Works in Win10 too. I just needed to define ```%USERPROFILE%\AppData\Local\whatsie\app.ico``` as icon.


> What does the folder C:\Users<your user name>\AppData\Local\whatsie contain on your machine?

From the last update:
![whatsie_update_bug3](https://cloud.githubusercontent.com/assets/37474/14584636/395f4b82-0426-11e6-92ab-aff2c9708c3f.PNG)

**Comment by Aluxian** [comment]
The shortcuts and notifications should be fixed in https://github.com/Aluxian/Whatsie/releases/tag/v2.0.14

**Comment by AdrianoCahete** [comment]
I didn't test shortcut 'cause i'm using @Kurobyte Fix.

Notification is fixed in this version. Thanks!

**Comment by Aluxian** [comment]
That's the same fix I applied in the new version 😄  👍
