### ISSUE TITLE
Energy impact on OSX

### ISSUE THREAD

**Issue by dbogdanov** [Aluxian/Whatsie#75]
Activity Monitor reports huge energy impact compared to other applications on my Macbook Pro. 

<img width="596" alt="screen shot 2016-04-18 at 12 03 42" src="https://cloud.githubusercontent.com/assets/409668/14600630/f71801e0-055d-11e6-8d50-bd0743056e7c.png">

**Comment by Aluxian** [comment]
You're still using the old app, WhatsApp for Desktop. Please switch to Whatsie by downloading it from this repository (the releases page, instructions are in the README).

**Comment by dbogdanov** [comment]
Closing this issue. I was testing Whatsie for the last hour, and haven't found this problem.

**Comment by Aluxian** [comment]
That's great to hear, thanks for the feedback!
