### ISSUE TITLE
Add the ability to show or hide the message tex...

### ISSUE THREAD

**Issue by Aluxian** [Aluxian/Whatsie#88]
**Description:**
Add the ability to show or hide the message text + sender name in the notification.

**Best thing about Whatsie:**
Ease of use,

**Worst thing about Whatsie:**
The entire message text + sender name shows up in the notifications

**Extra:**

**Comment by Aluxian** [comment]
Hmm, then they're not that useful anymore. Does anyone else have an opinion about this? IMO I don't think we should add this.

**Comment by sandeepraju** [comment]
I just figured out that there is already a way to do this. Adding the steps here in case someone wants to configure it.

## Step 01
![Click on the three vertically stacked dots and click on notifications](http://i.imgur.com/5wvTERB.png)

__Click on the three vertically stacked dots and click on notifications__

## Step 02
![Configure your notifications in the dialog box that appears](http://i.imgur.com/4oNIs2B.png)

__Configure your notifications in the dialog box that appears__
