### ISSUE TITLE
Neither audio nor visual notification within Windows 7

### ISSUE THREAD

**Issue by Aluxian** [Aluxian/Whatsie#92]
**Description:**
Neither audio nor visual notification within Windows 7

**Steps to reproduce:**
Nothing special just install and use

**App version:**
2.0.14-beta

**OS:**
Windows

**Extra:**

**Comment by aceintheplace** [comment]
Hi.
Same here. Same Version, no notifications

greetingz

**Comment by rusak** [comment]
Win7, audio notifications OK, tray icon changes color, no bubble notifications though.

**Comment by Aluxian** [comment]
Hey, this should be fixed in the latest version. Check for update inside the app or download Whatsie again from https://github.com/Aluxian/Whatsie/releases/tag/v2.0.18
