### ISSUE TITLE
The tray icon is showed truncated in Gnome Shell: http://...

### ISSUE THREAD

**Issue by Aluxian** [Aluxian/Whatsie#97]
**Description:**
The tray icon is showed truncated in Gnome Shell: http://pix.toile-libre.org/upload/original/1461224247.png

**Steps to reproduce:**
Open Whatsie in Gnome Shell with "Show in Tray" activated.

**App version:**
2.0.14-beta

**OS:**
Linux

**Extra:**
I think the tray icon should be a little smaller

**Comment by dionysius** [comment]
This might be the reason why I don't see no tray icon at all in ElementaryOS?

**Comment by Aluxian** [comment]
https://github.com/Aluxian/Whatsie/issues/98
