### ISSUE TITLE
[Linux] Tray icon is shown partially

### ISSUE THREAD

**Issue by simonbcn** [Aluxian/Whatsie#98]
Arch Linux 64 bits
Whatsie v2.0.14-beta (_this occurs in previous versions too_)
GNOME Shell 3.20.1

Open Whatsie with "Show in Tray" activated and this is the legacy tray icon shown in Gnome shell:
![menu_001](https://cloud.githubusercontent.com/assets/428231/14701607/861571c6-07a6-11e6-87c5-f7aaa52f71d3.png)

 I think the tray icon should be a little smaller.

**Comment by bil-elmoussaoui** [comment]
I think it's a bug with Gnome shell tray,  some other applications have this issue too (in my case : Telegram & Transmission)

**Comment by Aluxian** [comment]
I haven't found any reports in https://github.com/electron/electron. Since it's too low level to fix it, I'll close this assuming that it's probably a bug with Gnome shell, as @bil-elmoussaoui said.
