### ISSUE TITLE
[Linux] Tray icon doesn't respond to left click

### ISSUE THREAD

**Issue by simonbcn** [Aluxian/Whatsie#99]
Arch Linux 64 bits
Whatsie v2.0.14-beta
GNOME Shell 3.20.1

Whatsie with `Show in Tray` activated. I press the left mouse button but it doesn't respond, it does nothing. To show main window I have to press the right mouse button and select `Show Whatsie`.

**Comment by Aluxian** [comment]
Can you please try https://github.com/Aluxian/Whatsie/releases/tag/v2.0.13? Does it work for that version?

**Comment by simonbcn** [comment]
Yes, the version 2.0.13 works well.

**Comment by Aluxian** [comment]
Ah, it's a regression. I fixed it, expect an update soon :)

**Comment by Aluxian** [comment]
This should be live in the latest update (2.0.15). @simonbcn Can you please test this again?

**Comment by simonbcn** [comment]
Yes, it's solved.
